// Script to generate correct player replacements
const CORRECT_PLAYERS = [
  { id: '1', name: 'J. Chase', pos: 'WR', team: 'CIN' },
  { id: '2', name: 'B. Robinson', pos: 'RB', team: 'ATL' },
  { id: '3', name: 'C. Lamb', pos: 'WR', team: 'DAL' },
  { id: '4', name: 'J. Gibbs', pos: 'RB', team: 'DET' },
  { id: '5', name: 'D. Achane', pos: 'RB', team: 'MIA' },
  { id: '6', name: 'J. Jefferson', pos: 'WR', team: 'MIN' },
  { id: '7', name: 'S. Barkley', pos: 'RB', team: 'PHI' },
  { id: '8', name: 'C. McCaffrey', pos: 'RB', team: 'SF' },
  { id: '9', name: 'N. Collins', pos: 'WR', team: 'HOU' },
  { id: '10', name: 'M. Nabers', pos: 'WR', team: 'NYG' },
  { id: '11', name: 'P. Nuka', pos: 'WR', team: 'LAR' },
  { id: '12', name: 'A. Jeanty', pos: 'RB', team: 'LV' },
  { id: '13', name: 'A. St. Brown', pos: 'WR', team: 'DET' },
  { id: '14', name: 'B. Thomas', pos: 'WR', team: 'JAX' },
  { id: '15', name: 'A.J. Brown', pos: 'WR', team: 'PHI' },
  { id: '16', name: 'D. Henry', pos: 'RB', team: 'BAL' },
  { id: '17', name: 'J. Jacobs', pos: 'RB', team: 'GB' },
  { id: '18', name: 'B. Bowers', pos: 'TE', team: 'LV' },
  { id: '19', name: 'D. London', pos: 'WR', team: 'ATL' },
  { id: '20', name: 'C. Brown', pos: 'RB', team: 'CIN' },
  { id: '21', name: 'B. Irving', pos: 'RB', team: 'TB' },
  { id: '22', name: 'K. Williams', pos: 'RB', team: 'LAR' },
  { id: '23', name: 'J. Taylor', pos: 'RB', team: 'IND' },
  { id: '24', name: 'T. McBride', pos: 'TE', team: 'ARI' },
  { id: '25', name: 'T. Higgins', pos: 'WR', team: 'CIN' },
  { id: '26', name: 'L. McConkey', pos: 'WR', team: 'LAC' },
  { id: '27', name: 'J. Smith-Njigba', pos: 'WR', team: 'SEA' },
  { id: '28', name: 'L. Jackson', pos: 'QB', team: 'BAL' },
  { id: '29', name: 'J. Allen', pos: 'QB', team: 'BUF' },
  { id: '30', name: 'J. Daniels', pos: 'QB', team: 'WAS' },
  { id: '31', name: 'T. Hill', pos: 'WR', team: 'MIA' },
  { id: '32', name: 'K. Walker III', pos: 'RB', team: 'SEA' },
  { id: '33', name: 'D. Adams', pos: 'WR', team: 'LAR' },
  { id: '34', name: 'J. Cook', pos: 'RB', team: 'BUF' },
  { id: '35', name: 'G. Kittle', pos: 'TE', team: 'SF' },
  { id: '36', name: 'C. Hubbard', pos: 'RB', team: 'CAR' },
  { id: '37', name: 'O. Hampton', pos: 'RB', team: 'LAC' },
  { id: '38', name: 'B. Hall', pos: 'RB', team: 'NYJ' },
  { id: '39', name: 'G. Wilson', pos: 'WR', team: 'NYJ' },
  { id: '40', name: 'J. Burrow', pos: 'QB', team: 'CIN' },
  { id: '41', name: 'A. Kamara', pos: 'RB', team: 'NO' },
  { id: '42', name: 'J. Hurts', pos: 'QB', team: 'PHI' },
  { id: '43', name: 'T. Henderson', pos: 'RB', team: 'NE' },
  { id: '44', name: 'DK. Metcalf', pos: 'WR', team: 'PIT' },
  { id: '45', name: 'C. Sutton', pos: 'WR', team: 'DEN' },
  { id: '46', name: 'M. Evans', pos: 'WR', team: 'TB' },
  { id: '47', name: 'J. Connor', pos: 'RB', team: 'ARI' },
  { id: '48', name: 'M. Harrison Jr.', pos: 'WR', team: 'ARI' },
  { id: '49', name: 'X. Worthy', pos: 'WR', team: 'KC' },
  { id: '50', name: 'T. McMillan', pos: 'WR', team: 'CAR' },
  { id: '51', name: 'RJ. Harvey', pos: 'RB', team: 'DEN' },
  { id: '52', name: 'DJ. Moore', pos: 'WR', team: 'CHI' },
  { id: '53', name: 'T. McLaurin', pos: 'WR', team: 'WAS' },
  { id: '54', name: 'D. Swift', pos: 'RB', team: 'CHI' },
  { id: '55', name: 'J. Jeudy', pos: 'WR', team: 'CLE' },
  { id: '56', name: 'T. Pollard', pos: 'RB', team: 'TEN' },
  { id: '57', name: 'T. Hunter', pos: 'WR', team: 'JAX' },
  { id: '58', name: 'J. Williams', pos: 'WR', team: 'DET' },
  { id: '59', name: 'R. Rice', pos: 'WR', team: 'KC' },
  { id: '60', name: 'D. Smith', pos: 'WR', team: 'PHI' }
];

// Generate edit commands for each player
CORRECT_PLAYERS.forEach(player => {
  console.log(`Edit player ${player.id}:`);
  console.log(`name: '${player.name}', position: '${player.pos}', team: '${player.team}'`);
});