// Auction draft engine. The player pool and every number attached to it are
// generated by scripts/build-player-pool.mjs from nflverse data; see CLAUDE.md.
import poolData from '@/data/nfl/pool.json';
import {
  DEFAULT_LEAGUE,
  leagueShape,
  normaliseLeague,
  pricePool,
  sameLeague,
  startingSlots,
  unfilledSlotsFor,
  type LeagueShape,
} from '@/lib/valuation';
import type { RankingOverride } from '@/lib/rankingsCsv';

interface PoolEntry {
  gsis: string;
  name: string;
  position: string;
  team: string;
  tier: number;
  rank: number;
  auctionValue: number;
  vorp: number;
  ceiling: number;
  floor: number;
  consistency: number;
  byeWeek: number | null;
  age: number | null;
  experience: number | null;
  lastSeasonGames: number | null;
  snapShare: number | null;
  targetShare: number | null;
  injuryRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  ageRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  role: 'LOCKED_STARTER' | 'MINOR_COMPETITION' | 'TIMESHARE' | 'COMMITTEE';
  trend: 'RISING' | 'STABLE' | 'DECLINING' | 'UNPROVEN';
  projection: { points: number; pointsPerGame: number; expectedGames: number };
  percentiles?: Record<string, number>;
  usage?: PlayerUsage | null;
  context?: TeamContext | null;
  durability?: Durability;
  competition?: DepthCompetition;
  market?: MarketRead;
  breakoutSeason?: number | null;
  draft?: { year: number; round: number; pick: number; team: string } | null;
  defense?: {
    sacks: number;
    interceptions: number;
    fumbleRecoveries: number;
    touchdowns: number;
    safeties: number;
    pointsAllowedPerGame: number | null;
  };
}

export interface Player {
  id: string;
  name: string;
  position: 'QB' | 'RB' | 'WR' | 'TE' | 'K' | 'DST';
  team: string;
  tier: 1 | 2 | 3 | 4;
  baseValue: number;
  estimatedValue: number;
  /**
   * What our own model says, kept even when an imported ranking has replaced
   * the value everything else reads. Facts and opinions stay distinguishable:
   * the board can show whose number it is showing.
   */
  modelValue: number;
  /** Present only when an imported ranking is overriding this player. */
  customRanking?: RankingOverride;
  projectedPoints: number;
  adp: number; // Average Draft Position
  injuryRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  strengthOfSchedule?: number; // 1-10 scale
  valueOverReplacement: number; // VORP
  upside: number; // Ceiling projection
  floor: number; // Floor projection
  consistency: number; // Week-to-wave variance (1-10)
  byeWeek: number;
  ageRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  targetShare?: number; // Expected target/touch share %
  redZoneShare?: number; // Red zone opportunity %
  // Enhanced real data fields
  age?: number;
  experience?: number; // Years in NFL
  lastSeasonGames?: number;
  careerGames?: number;
  injuryHistory?: string[]; // List of past injuries
  contractStatus?: 'SECURE' | 'EXPIRING' | 'ROOKIE' | 'FRANCHISE_TAG';
  coachingStability?: 'STABLE' | 'NEW_COACH' | 'NEW_SYSTEM';
  offensiveLineRank?: number; // 1-32 team rank
  defensiveStrengthVsPosition?: number; // Opponent strength vs position
  weatherConcerns?: boolean; // Dome vs outdoor team
  playoffSchedule?: 'EASY' | 'MODERATE' | 'DIFFICULT';
  handcuffValue?: number; // Value if starter injured (0-100)
  primaryBackup?: string; // Name of primary backup
  competitionLevel: 'LOCKED_STARTER' | 'MINOR_COMPETITION' | 'TIMESHARE' | 'COMMITTEE';
  teamPaceRank?: number; // Team pace ranking (1-32)
  redZoneTouchesLastSeason?: number;
  snapPercentage?: number; // Expected snap %
  recentTrends: 'RISING' | 'STABLE' | 'DECLINING';
  fantasyRelevantWeeks?: number; // Weeks likely to be fantasy relevant
  floorWeeks?: number; // Number of weeks hitting floor
  ceilingWeeks?: number; // Number of weeks hitting ceiling
  /** Where each headline number sits among players at the same position, 0-100. */
  percentiles?: Record<string, number>;
  pointsPerGame?: number;
  expectedGames?: number;
  usage?: PlayerUsage | null;
  teamContext?: TeamContext | null;
  durability?: Durability;
  competition?: DepthCompetition;
  market?: MarketRead;
  breakoutSeason?: number | null;
  draftCapital?: { year: number; round: number; pick: number; team: string } | null;
  /** Team defense season totals. Present only for DST entries. */
  defense?: {
    sacks: number;
    interceptions: number;
    fumbleRecoveries: number;
    touchdowns: number;
    safeties: number;
    pointsAllowedPerGame: number | null;
  };
  isDrafted: boolean;
  draftedBy?: string;
  draftCost?: number;
  pickNumber?: number;
}

/** How a player's touches were earned, from the most recent season with a real
 *  sample. Volume is the projection; this is the shape of it. */
export interface PlayerUsage {
  season: number;
  games: number;
  targetShare: number | null;
  airYardsShare: number | null;
  wopr: number | null;
  adot: number | null;
  yacPerReception: number | null;
  carryShare: number | null;
  touchesPerGame: number | null;
  targetsPerGame: number | null;
  redZoneTouches: number;
  redZoneShare: number | null;
  goalLineTouches: number;
  firstDownsPerGame: number | null;
  epaPerTouch: number | null;
  passingEpa: number | null;
}

/** The offence a player lines up in. Opportunity is granted by a team before it
 *  is earned by a player. */
export interface TeamContext {
  playsPerGame: number;
  secondsPerPlay: number | null;
  neutralPassRate: number | null;
  passRateOverExpected: number | null;
  sackRateAllowed: number | null;
  epaPerPlay: number | null;
  redZoneTripsPerGame: number;
}

export interface Durability {
  seasons: Array<{ season: number; missed: number }>;
  totalMissed: number;
  /** Weeks on the injury report by body part — treatment, not absences. */
  reported: Array<{ part: string; weeks: number }>;
}

export interface DepthCompetition {
  depth: number;
  roomSize: number;
  aheadBy: number | null;
  behindBy: number | null;
  nextUp: string | null;
  starterAhead: string | null;
}

/** FantasyPros expert consensus, which ships its own disagreement. */
export interface MarketRead {
  consensusRank: number | null;
  positionRank: number | null;
  rawEcr: number | null;
  best: number | null;
  worst: number | null;
  spread: number | null;
  ownership: number | null;
  searchRank: number | null;
  depthChartOrder: number | null;
  source: string;
  asOf: string | null;
  /** Consensus rank minus our rank. Positive means the room is sleeping on him. */
  edge: number | null;
}

export type PlayerPosition = 'QB' | 'RB' | 'WR' | 'TE' | 'K' | 'DST';

/** Roster counts by position. Every draftable position needs a key here — a
 *  missing one turns `roster[position]++` into NaN and poisons depth scoring. */
export type RosterCounts = Record<PlayerPosition, number>;

export interface BidRejection {
  ok: false;
  /** Machine-readable so the UI can decide how loudly to complain. */
  code:
    | 'unknown-player'
    | 'unknown-team'
    | 'already-drafted'
    | 'invalid-amount'
    | 'insufficient-funds'
    | 'roster-full'
    | 'position-full';
  message: string;
}

export type BidCheck = { ok: true } | BidRejection;

export interface Team {
  id: string;
  name: string;
  budget: number;
  spent: number;
  remaining: number;
  roster: RosterCounts;
  projectedTotal: number;
  strengthScore: number;
  riskScore: number;
  depthScore: number;
  injuryInsurance: number;
}

export interface DraftAnalytics {
  baseValue: number;
  adjustedValue: number;
  maxBid: number;
  openingBid: number;
  targetBid: number;
  walkAwayPoint: number;
  needMultiplier: number;
  scarcityFactor: number;
  confidenceLevel: number;
  marketInflation: number;
  regressionRisk?: number;
  breakoutPotential?: number;
  positionScarcity: number;
  valueOverBaseline: number;
  riskAdjustedValue: number;
  optimalBidRange: [number, number];
  // Enhanced analytics
  injuryAdjustment: number;
  ageAdjustment: number;
  contractSecurityScore?: number;
  coachingStabilityScore?: number;
  teamEnvironmentScore?: number;
  competitionRisk: number;
  handcuffRecommendation?: string;
  backupTargets?: string[];
  idealDraftPosition?: string;
  rosterId: string;
}

/** What the room is doing with its money, derived entirely from the pick log. */
export interface MarketState {
  inflation: number;
  premium: number | null;
  moneyLeft: number;
  valueLeft: number;
  scarcity: Array<{
    position: PlayerPosition;
    gone: number;
    total: number;
    tierOneLeft: number;
    /** What the room paid against our list at this position, once two have sold. */
    premium: number | null;
    sold: number;
    /** Points between the best player left here and the fifth: the cost of waiting. */
    cliff: number;
  }>;
}

export interface DraftState {
  players: Player[];
  teams: Team[];
  draftedCount: number;
  totalPlayers: number;
  currentPick: number;
}

export interface SnakeDraftPlayer {
  id: string;
  name: string;
  position: 'QB' | 'RB' | 'WR' | 'TE' | 'K' | 'DST';
  team: string;
  tier: 1 | 2 | 3 | 4 | 5;
  baseValue: number;
  estimatedValue: number;
  projectedPoints: number;
  adp: number;
  injuryRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  strengthOfSchedule: number;
  valueOverReplacement: number;
  upside: number;
  floor: number;
  consistency: number;
  byeWeek: number;
  ageRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  targetShare: number;
  redZoneShare: number;
  age: number;
  experience: number;
  lastSeasonGames: number;
  careerGames: number;
  injuryHistory: string[];
  contractStatus: 'SECURE' | 'EXPIRING' | 'ROOKIE' | 'FRANCHISE_TAG';
  coachingStability: 'STABLE' | 'NEW_COACH' | 'NEW_SYSTEM';
  offensiveLineRank: number;
  defensiveStrengthVsPosition: number;
  weatherConcerns: boolean;
  playoffSchedule: 'EASY' | 'MODERATE' | 'DIFFICULT';
  handcuffValue: number;
  primaryBackup?: string;
  competitionLevel: 'LOCKED_STARTER' | 'MINOR_COMPETITION' | 'TIMESHARE' | 'COMMITTEE';
  teamPaceRank: number;
  redZoneTouchesLastSeason: number;
  snapPercentage: number;
  recentTrends: 'RISING' | 'STABLE' | 'DECLINING';
  fantasyRelevantWeeks: number;
  floorWeeks: number;
  ceilingWeeks: number;
  // Enhanced snake draft specific analytics
  breakoutPotential: number;
  regressionRisk: number;
  rookieProjection?: number;
  coachingFit: number;
  opportunityRank: number;
  depthChart: number;
  sleeper: boolean;
  bustRisk: number;
  weeklyVolatility: number;
  positionalScarcity: number;
  handcuffRecommendation: string;
  isDrafted: boolean;
  draftedBy?: string;
  pickNumber?: number;
}

/**
 * The league the shipped pool was priced for.
 *
 * Read from pool.json rather than restated, so that regenerating the pool for a
 * different shape moves the client's default with it. Everything downstream
 * reads `this.league`, which starts here and can be changed at runtime.
 */
const POOL_LEAGUE: LeagueShape = leagueShape(
  (poolData as { league?: Partial<LeagueShape> }).league ?? DEFAULT_LEAGUE
);

/**
 * The chosen league, kept apart from the pick log.
 *
 * It is a league-wide fact rather than a per-person preference, so it does not
 * belong in `use-draft-preferences`; but it is also not a pick, and the pick
 * log deliberately stores nothing derived. Its own key keeps both rules intact.
 */
const LEAGUE_STORAGE_KEY = 'draft-vault:league:v1';

const readStoredLeague = (): LeagueShape => {
  try {
    const raw = localStorage.getItem(LEAGUE_STORAGE_KEY);
    if (!raw) return POOL_LEAGUE;
    return normaliseLeague(leagueShape(JSON.parse(raw) as Partial<LeagueShape>));
  } catch {
    // Unparseable or unavailable storage falls back to the league the pool was
    // priced for, which is always a valid one.
    return POOL_LEAGUE;
  }
};

const writeStoredLeague = (league: LeagueShape): void => {
  try {
    if (sameLeague(league, POOL_LEAGUE)) localStorage.removeItem(LEAGUE_STORAGE_KEY);
    else localStorage.setItem(LEAGUE_STORAGE_KEY, JSON.stringify(league));
  } catch {
    /* storage unavailable — the league simply won't be remembered */
  }
};

/**
 * Somebody else's rankings, laid over ours.
 *
 * An import is an opinion — the whole point of it is to disagree with the
 * model — so it is stored apart from both the pick log and the league, and the
 * model's own number survives underneath it on every player.
 */
const RANKINGS_STORAGE_KEY = 'draft-vault:custom-rankings:v1';

/**
 * The draft a reset threw away.
 *
 * Reset sits next to Undo in the toolbar and used to be one unrecoverable
 * click: the pick log was deleted outright. Since the pick log is the only
 * shared fact, keeping the last one aside makes a reset undoable — which
 * matters most on the night, when the draft in progress is the only copy of an
 * afternoon's work.
 */
const CLEARED_STORAGE_KEY = 'draft-vault:cleared-draft:v1';

const readStoredOverrides = (): Record<string, RankingOverride> => {
  try {
    const raw = localStorage.getItem(RANKINGS_STORAGE_KEY);
    const parsed = raw ? (JSON.parse(raw) as Record<string, RankingOverride>) : null;
    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    return {};
  }
};

const writeStoredOverrides = (overrides: Record<string, RankingOverride>): void => {
  try {
    if (!Object.keys(overrides).length) localStorage.removeItem(RANKINGS_STORAGE_KEY);
    else localStorage.setItem(RANKINGS_STORAGE_KEY, JSON.stringify(overrides));
  } catch {
    /* storage unavailable — the import simply won't survive a reload */
  }
};

const EMPTY_ROSTER = (): RosterCounts => ({ QB: 0, RB: 0, WR: 0, TE: 0, K: 0, DST: 0 });

const rosterSize = (roster: RosterCounts): number =>
  Object.values(roster).reduce((total, count) => total + count, 0);

export class AuctionDraftService {
  private players: Player[] = [];
  private teams: Team[] = [];
  private draftedCount = 0;
  /** Pick order, so the last one can be taken back. */
  private history: Array<{ playerId: string; teamId: string; cost: number }> = [];
  /**
   * The league being drafted. Every rule and every dollar value derives from
   * it, so changing it re-prices the board rather than merely relabelling it.
   */
  private league: LeagueShape = POOL_LEAGUE;
  /** Replacement points per position under the active league. */
  private replacement: Record<string, number> = {};
  /**
   * Starting slots per team, derived from the lineup.
   *
   * Capped at the roster size: a league that fields more players than it may
   * roster is refused by the settings panel, but if one ever reached the engine
   * the dollar reserve would exceed every budget and no bid could be legal.
   */
  private get startingSlots(): number {
    return Math.min(this.league.rosterSize, startingSlots(this.league));
  }
  /** Imported rankings, by player id. Empty unless somebody has imported some. */
  private overrides: Record<string, RankingOverride> = readStoredOverrides();
  /** Told after every change that reached storage, so other windows can follow. */
  private onChanged: (() => void) | null = null;
  /**
   * True while rebuilding from a change another window made.
   *
   * Replaying a saved draft writes to storage on every pick, so without this
   * the rebuild would announce itself back and the two windows would rebuild
   * each other in a loop.
   */
  private applyingRemote = false;

  constructor(league: LeagueShape = readStoredLeague()) {
    this.league = normaliseLeague(league);
    this.initializePlayers();
    this.initializeTeams();
  }

  /**
   * The pool is generated, not typed by hand: scripts/build-player-pool.mjs
   * derives it from nflverse rosters and production, and every field below
   * traces back to a real observation or to the documented projection model.
   */
  private initializePlayers(): void {
    const entries = poolData.players as PoolEntry[];

    // The pool ships values for the league it was built for. Rather than trust
    // them, re-derive from projected points — which are league-independent —
    // through the same module the builder used. At the default shape this
    // reproduces the stored numbers exactly (there is a test that says so),
    // and at any other shape it is the only way they could be right.
    const { replacement, priced } = pricePool(
      entries.map((entry) => ({ position: entry.position, points: entry.projection.points })),
      this.league
    );
    this.replacement = replacement;

    this.players = entries.map((entry, index) => this.buildPlayer(entry, priced[index]));
  }

  /**
   * One pool entry, priced for this league and then overlaid with any imported
   * ranking. The model's number stays on `modelValue` either way, so nothing
   * downstream has to choose between showing ours and showing theirs.
   */
  private buildPlayer(entry: PoolEntry, priced: { vorp: number; auctionValue: number }): Player {
    const override = this.overrides[entry.gsis];
    const value = override?.value ?? priced.auctionValue;

    return {
      id: entry.gsis,
      name: entry.name,
      position: entry.position as PlayerPosition,
      team: entry.team,
      tier: (override?.tier ?? entry.tier) as 1 | 2 | 3 | 4,
      // Both follow the import: an opinion nobody's advice reflects is decoration.
      baseValue: value,
      estimatedValue: value,
      modelValue: priced.auctionValue,
      customRanking: override,
      projectedPoints: Math.round(entry.projection.points),
      // Rank by our own valuation. It is not an average draft position and is
      // not labelled as one.
      adp: override?.rank ?? entry.rank,
      injuryRisk: entry.injuryRisk,
      valueOverReplacement: Math.round(priced.vorp),
      upside: entry.ceiling,
      floor: entry.floor,
      consistency: entry.consistency,
      byeWeek: entry.byeWeek ?? 0,
      ageRisk: entry.ageRisk,
      age: entry.age ?? undefined,
      experience: entry.experience ?? undefined,
      lastSeasonGames: entry.lastSeasonGames ?? undefined,
      competitionLevel: entry.role,
      snapPercentage: entry.snapShare ?? undefined,
      targetShare: entry.targetShare ?? undefined,
      recentTrends: entry.trend === 'UNPROVEN' ? 'STABLE' : entry.trend,
      percentiles: entry.percentiles,
      pointsPerGame: entry.projection.pointsPerGame,
      expectedGames: entry.projection.expectedGames,
      usage: entry.usage ?? null,
      teamContext: entry.context ?? null,
      durability: entry.durability,
      competition: entry.competition,
      market: entry.market,
      breakoutSeason: entry.breakoutSeason ?? null,
      draftCapital: entry.draft ?? null,
      defense: entry.defense,
      isDrafted: false,
    };
  }

  private initializeTeams(): void {
    this.teams = Array.from({ length: this.league.teams }, (_, i) => ({
      id: `team-${i + 1}`,
      name: `Team ${i + 1}`,
      budget: this.league.budget,
      spent: 0,
      remaining: this.league.budget,
      roster: EMPTY_ROSTER(),
      projectedTotal: 0,
      strengthScore: 0,
      riskScore: 0,
      depthScore: 0,
      injuryInsurance: 0,
    }));
  }

  /** A fresh array each call: callers compare references to detect changes. */
  getPlayers(): Player[] {
    return [...this.players];
  }

  getTeams(): Team[] {
    return [...this.teams];
  }

  getDraftState(): DraftState {
    return {
      players: [...this.players],
      teams: [...this.teams],
      draftedCount: this.draftedCount,
      totalPlayers: this.players.length,
      currentPick: this.draftedCount + 1,
    };
  }

  /**
   * Whether this bid is legal, and if not, why.
   *
   * Callers should run this before offering a bid so the reason can be shown;
   * draftPlayer enforces it again regardless.
   */
  validateBid(playerId: string, teamId: string, cost: number): BidCheck {
    const player = this.players.find((p) => p.id === playerId);
    if (!player)
      return { ok: false, code: 'unknown-player', message: 'That player is not in the pool.' };
    if (player.isDrafted) {
      const owner = this.teams.find((t) => t.id === player.draftedBy);
      return {
        ok: false,
        code: 'already-drafted',
        message: `${player.name} already went to ${owner?.name ?? 'another team'} for $${player.draftCost}.`,
      };
    }

    const team = this.teams.find((t) => t.id === teamId);
    if (!team) return { ok: false, code: 'unknown-team', message: 'Pick a team first.' };

    // NaN fails every comparison, so it has to be rejected explicitly or it
    // sails through the budget check and turns the team's money into NaN.
    if (!Number.isInteger(cost) || cost < 1) {
      return {
        ok: false,
        code: 'invalid-amount',
        message: 'A bid must be a whole dollar amount of $1 or more.',
      };
    }

    const filled = rosterSize(team.roster);
    if (filled >= this.league.rosterSize) {
      return {
        ok: false,
        code: 'roster-full',
        message: `${team.name} already has ${this.league.rosterSize} players.`,
      };
    }
    if (team.roster[player.position] >= this.league.positionLimits[player.position]) {
      return {
        ok: false,
        code: 'position-full',
        message: `${team.name} cannot carry more than ${this.league.positionLimits[player.position]} at ${player.position}.`,
      };
    }

    // Every remaining starting slot still needs at least a dollar to fill.
    const slotsToFill = Math.max(0, this.startingSlots - filled - 1);
    const spendable = team.remaining - slotsToFill;
    if (cost > spendable) {
      return {
        ok: false,
        code: 'insufficient-funds',
        message:
          slotsToFill > 0
            ? `${team.name} can spend $${Math.max(0, spendable)} — $${slotsToFill} is held back for ${slotsToFill} open starting spot${slotsToFill === 1 ? '' : 's'}.`
            : `${team.name} only has $${team.remaining} left.`,
      };
    }

    return { ok: true };
  }

  draftPlayer(playerId: string, teamId: string, cost: number): boolean {
    if (!this.validateBid(playerId, teamId, cost).ok) return false;

    const player = this.players.find((p) => p.id === playerId)!;
    const team = this.teams.find((t) => t.id === teamId)!;

    player.isDrafted = true;
    player.draftedBy = teamId;
    player.draftCost = cost;
    player.pickNumber = this.draftedCount + 1;

    team.spent += cost;
    team.remaining -= cost;
    team.roster[player.position]++;
    team.projectedTotal += player.projectedPoints;

    this.draftedCount++;
    this.history.push({ playerId, teamId, cost });
    this.updateTeamMetrics(team);
    this.persist();

    return true;
  }

  /** Takes back the most recent pick. Returns the undone pick, or null. */
  undoLastPick(): { player: Player; team: Team; cost: number } | null {
    const last = this.history.pop();
    if (!last) return null;

    const player = this.players.find((p) => p.id === last.playerId);
    const team = this.teams.find((t) => t.id === last.teamId);
    if (!player || !team) return null;

    player.isDrafted = false;
    delete player.draftedBy;
    delete player.draftCost;
    delete player.pickNumber;

    team.spent -= last.cost;
    team.remaining += last.cost;
    team.roster[player.position] = Math.max(0, team.roster[player.position] - 1);
    team.projectedTotal -= player.projectedPoints;

    this.draftedCount = Math.max(0, this.draftedCount - 1);
    this.updateTeamMetrics(team);
    this.persist();

    return { player, team, cost: last.cost };
  }

  /**
   * Whose turn it is to nominate.
   *
   * Derived from the number of picks made rather than stored, so it can never
   * drift out of step with the draft and needs nothing extra synchronised if
   * this ever runs on more than one screen.
   */
  /**
   * Whether this team can still add anybody.
   *
   * A full roster is the practical end of a team's draft: the reserve rules
   * guarantee it can always afford a dollar for each open slot, so money never
   * strands a team with room.
   */
  canDraft(team: Team): boolean {
    return rosterSize(team.roster) < this.league.rosterSize;
  }

  /** True once no team has room for another player. */
  isComplete(): boolean {
    return this.teams.length > 0 && this.teams.every((team) => !this.canDraft(team));
  }

  /**
   * Whose turn it is to nominate.
   *
   * Rotation is still derived from the pick count rather than stored, but it
   * steps over teams that are full — a team whose roster is finished does not
   * keep getting handed the nomination, and at the end of the draft nobody is.
   */
  getNominatingTeam(): Team | undefined {
    if (!this.teams.length) return undefined;
    const start = this.draftedCount % this.teams.length;
    for (let step = 0; step < this.teams.length; step++) {
      const team = this.teams[(start + step) % this.teams.length];
      if (this.canDraft(team)) return team;
    }
    return undefined;
  }

  /** Nomination order from here, starting with whoever is up. */
  getNominationOrder(count = 4): Team[] {
    return Array.from(
      { length: Math.min(count, this.teams.length) },
      (_, offset) => this.teams[(this.draftedCount + offset) % this.teams.length]
    );
  }

  /**
   * How the room is behaving, as numbers a bidder can act on.
   *
   * Inflation above 1 means more money is chasing less value than the list
   * prices assume, so everything left will go for more than it says on the tin.
   * The premium is what has actually happened so far: what the room paid
   * divided by what we said those players were worth.
   */
  getMarketState(): MarketState {
    const drafted = this.players.filter((p) => p.isDrafted);
    const spent = drafted.reduce((total, p) => total + (p.draftCost ?? 0), 0);
    const listed = drafted.reduce((total, p) => total + p.estimatedValue, 0);

    const positions: PlayerPosition[] = ['QB', 'RB', 'WR', 'TE', 'K', 'DST'];
    const scarcity = positions.map((position) => {
      const startable = this.players.filter((p) => p.position === position && p.estimatedValue > 1);
      const sold = drafted.filter((p) => p.position === position);
      const soldFor = sold.reduce((total, p) => total + (p.draftCost ?? 0), 0);
      const soldList = sold.reduce((total, p) => total + p.estimatedValue, 0);

      // The drop from the best player left to the fifth-best: how much it costs
      // to wait. A big cliff is why a position becomes urgent.
      const remaining = startable
        .filter((p) => !p.isDrafted)
        .sort((a, b) => b.projectedPoints - a.projectedPoints);
      const cliff =
        remaining.length > 4
          ? Math.round(remaining[0].projectedPoints - remaining[4].projectedPoints)
          : 0;

      return {
        position,
        gone: startable.filter((p) => p.isDrafted).length,
        total: startable.length,
        tierOneLeft: this.players.filter(
          (p) => p.position === position && p.tier === 1 && !p.isDrafted
        ).length,
        /** What the room paid for this position against our list, once two have sold. */
        premium: sold.length >= 2 && soldList > 0 ? soldFor / soldList : null,
        sold: sold.length,
        cliff,
      };
    });

    return {
      inflation: this.calculateMarketInflation(),
      premium: listed > 0 ? spent / listed : null,
      moneyLeft: this.teams.reduce((total, team) => total + team.remaining, 0),
      valueLeft: this.players
        .filter((p) => !p.isDrafted && p.estimatedValue > 1)
        .reduce((total, p) => total + p.estimatedValue, 0),
      scarcity,
    };
  }

  /**
   * Replacement level per position, straight from the generated pool.
   *
   * Deliberately read rather than recomputed: it falls out of the league shape
   * in scripts/build-player-pool.mjs, and a second definition here would be a
   * third copy of LEAGUE to keep in step.
   */
  getReplacementLevel(position: PlayerPosition): number | null {
    return this.replacement[position] ?? null;
  }

  /** The league in force. Every value on the board was priced for exactly this. */
  getLeagueShape(): LeagueShape {
    return {
      ...this.league,
      positionLimits: { ...this.league.positionLimits },
      rostered: { ...this.league.rostered },
    };
  }

  /** The league the shipped pool was generated for, for showing what changed. */
  getPoolLeagueShape(): LeagueShape {
    return {
      ...POOL_LEAGUE,
      positionLimits: { ...POOL_LEAGUE.positionLimits },
      rostered: { ...POOL_LEAGUE.rostered },
    };
  }

  /**
   * How many players the pool actually holds at each position.
   *
   * A league may roster more of a position than exist in the pool — 32 teams
   * want 53 quarterbacks and there are 40 — and `replacementLevels` then falls
   * back to the worst one rather than erroring, which understates that
   * position's values. Nothing about that is visible from the board, so the
   * settings panel says it before a league is applied.
   */
  getPoolDepth(): Record<string, number> {
    const depth: Record<string, number> = {};
    for (const player of this.players) {
      depth[player.position] = (depth[player.position] ?? 0) + 1;
    }
    return depth;
  }

  /** The imported rankings in force, by player id. */
  getCustomRankings(): Record<string, RankingOverride> {
    return { ...this.overrides };
  }

  /** How many players an import is currently speaking for. */
  getCustomRankingCount(): number {
    return Object.keys(this.overrides).length;
  }

  /**
   * Lay an imported ranking over the board.
   *
   * Unlike a league change this does not invalidate picks already made — the
   * money spent is still the money spent — so a draft in progress survives it.
   * Only what the remaining players are said to be worth moves.
   */
  setCustomRankings(overrides: Record<string, RankingOverride>): void {
    this.overrides = { ...overrides };
    writeStoredOverrides(this.overrides);
    this.repriceInPlace();
    this.announce();
  }

  /** Drop the import and go back to what the model says. */
  clearCustomRankings(): void {
    if (!Object.keys(this.overrides).length) return;
    this.overrides = {};
    writeStoredOverrides(this.overrides);
    this.repriceInPlace();
    this.announce();
  }

  /**
   * Rebuild the pool's valuations while keeping the draft that is under way.
   *
   * Rebuilding outright would drop who owns whom, so each player is rebuilt
   * from the pool and then has its draft state copied back on.
   */
  private repriceInPlace(): void {
    const state = new Map(
      this.players.map((player) => [
        player.id,
        {
          isDrafted: player.isDrafted,
          draftedBy: player.draftedBy,
          draftCost: player.draftCost,
          pickNumber: player.pickNumber,
        },
      ])
    );

    this.initializePlayers();

    for (const player of this.players) {
      const previous = state.get(player.id);
      if (!previous?.isDrafted) continue;
      player.isDrafted = true;
      player.draftedBy = previous.draftedBy;
      player.draftCost = previous.draftCost;
      player.pickNumber = previous.pickNumber;
    }
  }

  /**
   * Change the league, re-pricing the board.
   *
   * Every dollar value, replacement level and roster rule moves, so a draft in
   * progress cannot survive the change — its picks were made against prices
   * that no longer exist. The picks are cleared rather than silently
   * reinterpreted. Returns false when the shape would not change anything.
   */
  setLeagueShape(next: LeagueShape): boolean {
    const wanted = normaliseLeague(next);
    if (sameLeague(wanted, this.league)) return false;
    this.league = wanted;
    this.draftedCount = 0;
    this.history = [];
    this.initializePlayers();
    this.initializeTeams();
    writeStoredLeague(this.league);
    this.persist();
    return true;
  }

  /**
   * What a hypothetical purchase does to the rest of a roster.
   *
   * The number that actually decides a bid is not the price — it is what is left
   * per slot afterwards, and whether that still buys starters. This answers it
   * without committing anything.
   */
  simulateSpend(
    teamId: string,
    cost: number
  ): {
    remaining: number;
    slotsLeft: number;
    perSlot: number;
    /** Slots that must be filled at a dollar to stay legal. */
    minimumHold: number;
    /** True only when the amount is a real bid the reserve rules would allow. */
    /** Best player still on the board that the leftover budget could afford. */
    affordable: Player | null;
    legal: boolean;
  } | null {
    const team = this.teams.find((t) => t.id === teamId);
    if (!team) return null;

    const filled = Object.values(team.roster).reduce((a, b) => a + b, 0);
    const slotsLeft = Math.max(0, this.league.rosterSize - filled - 1);
    const remaining = team.remaining - cost;
    // Every unfilled starting slot still needs a dollar in reserve, exactly as
    // validateBid enforces it.
    const minimumHold = Math.max(0, this.startingSlots - filled - 1);
    const spendable = remaining - minimumHold;
    const affordable =
      spendable > 0
        ? (this.players
            .filter((p) => !p.isDrafted && p.id !== undefined && p.estimatedValue <= spendable)
            .sort((a, b) => b.projectedPoints - a.projectedPoints)[0] ?? null)
        : null;

    return {
      remaining,
      slotsLeft,
      perSlot: slotsLeft > 0 ? Math.max(0, remaining - minimumHold) / slotsLeft : 0,
      minimumHold,
      affordable,
      legal: remaining >= minimumHold && cost >= 1,
    };
  }

  /**
   * Where our board and the market's disagree, in dollars.
   *
   * `market.edge` is a difference of ranks; this converts it into what it is
   * worth tonight by pricing each player at the room's current inflation. A
   * player the consensus ranks 40 spots below us is only a bargain if he is
   * still going to be cheap when he comes up.
   */
  getBargains(limit = 24): Array<{
    player: Player;
    edge: number;
    listed: number;
    projectedCost: number;
    saving: number;
  }> {
    const inflation = this.calculateMarketInflation();
    return this.players
      .filter((p) => !p.isDrafted && p.market?.consensusRank != null && p.estimatedValue > 1)
      .map((player) => {
        const listed = player.estimatedValue;
        // The room bids off consensus, so the expected price tracks the market
        // rank, not ours; inflation moves both.
        const projectedCost = Math.max(1, Math.round(listed * inflation));
        return {
          player,
          edge: player.market?.edge ?? 0,
          listed,
          projectedCost,
          saving: Math.round(listed - projectedCost + (player.market?.edge ?? 0) * 0.12),
        };
      })
      .sort((a, b) => b.edge - a.edge || b.listed - a.listed)
      .slice(0, limit);
  }

  /** Every pick so far, grouped for the league board. */
  getDraftBoard(): Array<{
    team: Team;
    picks: Array<{ player: Player; cost: number; pickNumber: number }>;
  }> {
    return this.teams.map((team) => ({
      team,
      picks: this.players
        .filter((p) => p.draftedBy === team.id)
        .map((p) => ({ player: p, cost: p.draftCost ?? 0, pickNumber: p.pickNumber ?? 0 }))
        .sort((a, b) => a.pickNumber - b.pickNumber),
    }));
  }

  canUndo(): boolean {
    return this.history.length > 0;
  }

  private updateTeamMetrics(team: Team): void {
    const teamPlayers = this.players.filter((p) => p.draftedBy === team.id);

    // Calculate strength score (average projected points)
    team.strengthScore =
      teamPlayers.length > 0
        ? teamPlayers.reduce((sum, p) => sum + p.projectedPoints, 0) / teamPlayers.length
        : 0;

    // Calculate risk score (average injury risk)
    const riskValues = { LOW: 1, MEDIUM: 2, HIGH: 3 };
    team.riskScore =
      teamPlayers.length > 0
        ? teamPlayers.reduce((sum, p) => sum + riskValues[p.injuryRisk], 0) / teamPlayers.length
        : 0;

    // Players beyond the starting lineup. This read from its own QB1/RB2/WR2
    // table, which disagreed with the QB1/RB2/WR3 one urgency used — a third
    // receiver counted as bench depth and as a starter at the same time.
    team.depthScore = Object.entries(team.roster).reduce((total, [pos, count]) => {
      const starting = this.league.startingLineup[pos as PlayerPosition] ?? 0;
      return total + Math.max(0, count - starting);
    }, 0);

    // Calculate injury insurance (handcuff value)
    team.injuryInsurance = teamPlayers.reduce((sum, p) => sum + (p.handcuffValue ?? 0), 0) / 100;
  }

  /**
   * What this player should cost this team, right now.
   *
   * Three real forces move a price away from the list value: how much money is
   * still chasing how much value (inflation), how badly this team still needs
   * the position (need), and how little of the position is left (scarcity).
   * Nothing here is invented — each one is read off the current draft state.
   */
  generateDraftAnalytics(playerId: string, teamId: string): DraftAnalytics {
    const player = this.players.find((p) => p.id === playerId);
    const team = this.teams.find((t) => t.id === teamId);
    if (!player || !team) throw new Error('Player or team not found');

    const marketInflation = this.calculateMarketInflation();
    const needMultiplier = this.calculateNeedMultiplier(player.position, team);
    const positionScarcity = this.calculatePositionScarcity(player.position);

    const adjustedValue =
      player.baseValue * marketInflation * needMultiplier * (1 + positionScarcity * 0.15);

    // Injury and age history discount what we are willing to commit.
    const riskFactor =
      (player.injuryRisk === 'HIGH' ? 0.88 : player.injuryRisk === 'MEDIUM' ? 0.95 : 1) *
      (player.ageRisk === 'HIGH' ? 0.9 : player.ageRisk === 'MEDIUM' ? 0.96 : 1);
    const riskAdjustedValue = adjustedValue * riskFactor;

    const filled = Object.values(team.roster).reduce((total, count) => total + count, 0);
    const slotsToFill = Math.max(0, this.startingSlots - filled - 1);
    const spendable = Math.max(1, team.remaining - slotsToFill);

    const targetBid = Math.max(1, Math.round(riskAdjustedValue));
    const maxBid = Math.max(1, Math.min(Math.round(riskAdjustedValue * 1.15), spendable));
    const openingBid = Math.max(1, Math.round(targetBid * 0.6));

    return {
      baseValue: player.baseValue,
      adjustedValue: Math.round(adjustedValue),
      maxBid,
      openingBid,
      targetBid,
      // The first dollar you should not spend.
      walkAwayPoint: maxBid + 1,
      needMultiplier: Math.round(needMultiplier * 100) / 100,
      scarcityFactor: Math.round(positionScarcity * 100) / 100,
      confidenceLevel: this.calculateConfidenceLevel(player),
      marketInflation: Math.round(marketInflation * 100) / 100,
      positionScarcity: Math.round(positionScarcity * 100) / 100,
      valueOverBaseline: player.valueOverReplacement,
      riskAdjustedValue: Math.round(riskAdjustedValue),
      optimalBidRange: [openingBid, maxBid],
      injuryAdjustment: Math.round((1 - riskFactor) * 100) / 100,
      ageAdjustment: player.ageRisk === 'LOW' ? 0 : player.ageRisk === 'MEDIUM' ? 0.04 : 0.1,
      competitionRisk: player.competitionLevel === 'LOCKED_STARTER' ? 0 : 0.15,
      rosterId: team.id,
    };
  }

  /**
   * Dollars still available divided by the value still on the board. Above 1.0
   * the room is going to overpay for what is left; below it, bargains.
   */
  private calculateMarketInflation(): number {
    const openSlots = this.teams.reduce(
      (total, team) =>
        total +
        Math.max(0, this.startingSlots - Object.values(team.roster).reduce((a, b) => a + b, 0)),
      0
    );
    const moneyLeft = this.teams.reduce((total, team) => total + team.remaining, 0) - openSlots;
    const valueLeft = this.players
      .filter((p) => !p.isDrafted && p.estimatedValue > 1)
      .reduce((total, p) => total + p.estimatedValue, 0);
    if (valueLeft <= 0) return 1;
    return Math.max(0.6, Math.min(1.8, moneyLeft / valueLeft));
  }

  /**
   * How urgently this team still needs the position.
   *
   * An empty slot early is not urgent — there is a whole draft left to fill it.
   * The premium therefore grows with how much of the position is already gone,
   * which is what actually makes a hole expensive.
   */
  private calculateNeedMultiplier(position: string, team: Team): number {
    // Derived from the league's own lineup, so a superflex or a 3-WR league
    // makes the positions it actually starts urgent, and a flex counts for
    // every position that could fill it.
    const unfilled = unfilledSlotsFor(position as PlayerPosition, team.roster, this.league);
    const gone = this.calculatePositionScarcity(position);
    return 1 + Math.min(0.45, unfilled * 0.18 * gone);
  }

  /** Share of the position's startable players already off the board. */
  private calculatePositionScarcity(position: string): number {
    const startable = this.players.filter((p) => p.position === position && p.estimatedValue > 1);
    if (!startable.length) return 0;
    const gone = startable.filter((p) => p.isDrafted).length;
    return gone / startable.length;
  }

  /** How much of this player we have actually seen, on a 0-100 scale. */
  private calculateConfidenceLevel(player: Player): number {
    const games = player.lastSeasonGames ?? 0;
    const sample = Math.min(1, games / 17);
    const steadiness = (player.consistency ?? 5) / 10;
    return Math.round((sample * 0.6 + steadiness * 0.4) * 100);
  }

  isDraftComplete(): boolean {
    return this.draftedCount >= 60;
  }

  searchPlayers(query: string): Player[] {
    if (!query) return this.players;
    return this.players.filter(
      (p) =>
        p.name.toLowerCase().includes(query.toLowerCase()) ||
        p.position.toLowerCase().includes(query.toLowerCase()) ||
        p.team.toLowerCase().includes(query.toLowerCase())
    );
  }

  getPlayerAnalytics(playerId: string, teamId: string = 'team-1'): DraftAnalytics {
    return this.generateDraftAnalytics(playerId, teamId);
  }

  getDraftedPlayers(): Player[] {
    return this.players.filter((p) => p.isDrafted);
  }

  getAvailablePlayers(): Player[] {
    return this.players.filter((p) => !p.isDrafted);
  }

  resetDraft(): void {
    // Stash before clearing, so the reset can be taken back.
    if (this.history.length) {
      try {
        localStorage.setItem(
          CLEARED_STORAGE_KEY,
          JSON.stringify({
            clearedAt: new Date().toISOString(),
            league: this.league,
            budgets: this.teams.map((t) => ({ id: t.id, budget: t.budget })),
            picks: this.history,
          })
        );
      } catch {
        /* storage unavailable — the reset is simply not undoable */
      }
    }

    this.players.forEach((p) => {
      p.isDrafted = false;
      delete p.draftedBy;
      delete p.draftCost;
      delete p.pickNumber;
    });
    this.draftedCount = 0;
    this.history = [];
    this.teams.forEach((team) => {
      team.spent = 0;
      team.remaining = team.budget;
      team.roster = EMPTY_ROSTER();
      team.projectedTotal = 0;
      // Derived metrics too: leaving these behind makes a reset draft report
      // the strength and risk of the roster it just threw away.
      team.strengthScore = 0;
      team.riskScore = 0;
      team.depthScore = 0;
      team.injuryInsurance = 0;
    });
    this.persist();
  }

  // -------------------------------------------------------------------------
  // persistence
  //
  // Only the picks are stored: replaying them rebuilds every derived number, so
  // a saved draft can never disagree with the current valuation logic.
  // -------------------------------------------------------------------------

  /**
   * Watch for changes that reached storage.
   *
   * Deliberately carries nothing: a listener is being told the draft moved, not
   * what it moved to. Whatever it needs, it reads back from the engine, which
   * is the same rule that keeps the pick log the only shared fact.
   */
  setChangeListener(listener: (() => void) | null): void {
    this.onChanged = listener;
  }

  private announce(): void {
    if (this.applyingRemote) return;
    this.onChanged?.();
  }

  /**
   * Rebuild from what another window wrote.
   *
   * The whole state is re-derived from storage rather than patched, because a
   * patch would need to know what changed and the channel deliberately does not
   * say. Rebuilding cannot drift; a patch could.
   */
  reloadFromStorage(): void {
    this.applyingRemote = true;
    try {
      this.league = normaliseLeague(readStoredLeague());
      this.overrides = readStoredOverrides();
      this.draftedCount = 0;
      this.history = [];
      this.initializePlayers();
      this.initializeTeams();
      // Replays the pick log the other window just wrote. A cleared draft
      // leaves nothing to restore, which is the correct empty board.
      this.restore();
    } finally {
      this.applyingRemote = false;
    }
  }

  private persist(): void {
    try {
      // Emptying the draft is a change like any other. This used to `return`
      // here, which skipped the announcement below — so a second window
      // followed picks but never followed an undo back to zero, a reset, or a
      // league change (which clears the picks and so lands on this branch).
      if (!this.history.length) {
        localStorage.removeItem(AuctionDraftService.STORAGE_KEY);
      } else {
        localStorage.setItem(
          AuctionDraftService.STORAGE_KEY,
          JSON.stringify({
            version: 2,
            savedAt: new Date().toISOString(),
            // Stamped, not to be replayed from, but so a pick log cannot be
            // reinterpreted under a league it was never bid in. Absent on saves
            // written before leagues were configurable, which were all default.
            league: this.league,
            budgets: this.teams.map((t) => ({ id: t.id, budget: t.budget })),
            picks: this.history,
          })
        );
      }
    } catch {
      /* storage unavailable (private mode, quota) — the draft simply won't resume */
    }
    this.announce();
  }

  /** Replays a saved draft. Returns how many picks were restored. */
  restore(): number {
    let saved: {
      version?: number;
      league?: LeagueShape;
      budgets?: Array<{ id: string; budget: number }>;
      picks?: Array<{ playerId: string; teamId: string; cost: number }>;
    } | null = null;
    try {
      const raw = localStorage.getItem(AuctionDraftService.STORAGE_KEY);
      saved = raw ? JSON.parse(raw) : null;
    } catch {
      saved = null;
    }
    if (!saved?.picks?.length || saved.version !== 2) return 0;

    // Those bids bought players at prices this league does not charge. Replaying
    // them would produce a roster nobody could have afforded, so decline.
    const savedLeague = saved.league ? normaliseLeague(leagueShape(saved.league)) : POOL_LEAGUE;
    if (!sameLeague(savedLeague, this.league)) return 0;

    this.resetDraft();
    for (const { id, budget } of saved.budgets ?? []) this.updateTeamBudget(id, budget);

    let restored = 0;
    for (const pick of saved.picks) {
      if (this.draftPlayer(pick.playerId, pick.teamId, pick.cost)) restored++;
    }
    return restored;
  }

  /**
   * How many picks a reset threw away, if one can still be taken back.
   *
   * Only offered while the board is empty: once somebody drafts again the
   * cleared draft is genuinely history, and restoring it would silently
   * replace work done since.
   */
  clearedPickCount(): number {
    if (this.history.length) return 0;
    try {
      const raw = localStorage.getItem(CLEARED_STORAGE_KEY);
      const saved = raw ? (JSON.parse(raw) as { league?: LeagueShape; picks?: unknown[] }) : null;
      if (!saved?.picks?.length) return 0;
      // Prices moved on if the league changed; those bids no longer make sense.
      const league = saved.league ? normaliseLeague(leagueShape(saved.league)) : POOL_LEAGUE;
      return sameLeague(league, this.league) ? saved.picks.length : 0;
    } catch {
      return 0;
    }
  }

  /** Put back the draft the last reset cleared. Returns how many picks returned. */
  restoreClearedDraft(): number {
    if (this.history.length) return 0;
    let saved: {
      league?: LeagueShape;
      budgets?: Array<{ id: string; budget: number }>;
      picks?: Array<{ playerId: string; teamId: string; cost: number }>;
    } | null = null;
    try {
      const raw = localStorage.getItem(CLEARED_STORAGE_KEY);
      saved = raw ? JSON.parse(raw) : null;
    } catch {
      saved = null;
    }
    if (!saved?.picks?.length) return 0;

    const league = saved.league ? normaliseLeague(leagueShape(saved.league)) : POOL_LEAGUE;
    if (!sameLeague(league, this.league)) return 0;

    for (const { id, budget } of saved.budgets ?? []) this.updateTeamBudget(id, budget);
    let restored = 0;
    for (const pick of saved.picks) {
      if (this.draftPlayer(pick.playerId, pick.teamId, pick.cost)) restored++;
    }
    try {
      localStorage.removeItem(CLEARED_STORAGE_KEY);
    } catch {
      /* nothing to clean up */
    }
    return restored;
  }

  /**
   * The draft as a file somebody can keep.
   *
   * localStorage is one browser profile on one machine: a cleared cache, a
   * borrowed laptop or a dead battery loses the afternoon. This is the same
   * thing `persist()` writes, plus the league it was bid under, so a draft can
   * be carried somewhere else and picked up mid-auction.
   */
  exportDraft(): string {
    return JSON.stringify(
      {
        kind: 'draft-vault-draft',
        version: 1,
        savedAt: new Date().toISOString(),
        league: this.league,
        budgets: this.teams.map((t) => ({ id: t.id, budget: t.budget })),
        picks: this.history,
      },
      null,
      2
    );
  }

  /**
   * Load a draft from a file, replacing whatever is on the board.
   *
   * The league travels with the picks and is adopted, because prices are
   * meaningless without it — a draft bid in a ten-team league does not describe
   * a roster anybody could buy in a twelve-team one. Picks that no longer
   * validate are counted rather than silently dropped.
   */
  importDraft(
    text: string
  ): { ok: true; restored: number; skipped: number } | { ok: false; reason: string } {
    let saved: {
      kind?: string;
      league?: LeagueShape;
      budgets?: Array<{ id: string; budget: number }>;
      picks?: Array<{ playerId: string; teamId: string; cost: number }>;
    };
    try {
      saved = JSON.parse(text);
    } catch {
      return { ok: false, reason: 'That file is not a saved draft — it is not readable as JSON.' };
    }

    if (!saved || saved.kind !== 'draft-vault-draft') {
      return { ok: false, reason: 'That file was not saved by Draft Vault.' };
    }
    if (!Array.isArray(saved.picks)) {
      return { ok: false, reason: 'That draft file has no picks in it.' };
    }

    this.league = saved.league ? normaliseLeague(leagueShape(saved.league)) : this.league;
    writeStoredLeague(this.league);
    this.draftedCount = 0;
    this.history = [];
    this.initializePlayers();
    this.initializeTeams();

    for (const { id, budget } of saved.budgets ?? []) this.updateTeamBudget(id, budget);

    let restored = 0;
    for (const pick of saved.picks) {
      if (this.draftPlayer(pick.playerId, pick.teamId, pick.cost)) restored++;
    }
    this.persist();
    return { ok: true, restored, skipped: saved.picks.length - restored };
  }

  /** Whether a resumable draft is sitting in storage. */
  static hasSavedDraft(): boolean {
    try {
      return !!localStorage.getItem(AuctionDraftService.STORAGE_KEY);
    } catch {
      return false;
    }
  }

  private static readonly STORAGE_KEY = 'draft-vault:auction-draft:v2';

  getHistory(): ReadonlyArray<{ playerId: string; teamId: string; cost: number }> {
    return this.history;
  }

  getValueGrade(estimatedValue: number, actualCost: number): string {
    const ratio = actualCost / estimatedValue;
    if (ratio <= 0.8) return 'A+';
    if (ratio <= 0.9) return 'A';
    if (ratio <= 1.0) return 'B+';
    if (ratio <= 1.1) return 'B';
    if (ratio <= 1.2) return 'C';
    return 'D';
  }

  getProgressPercentage(): number {
    return (this.draftedCount / 60) * 100;
  }

  updateTeamBudget(teamId: string, budget: number): void {
    const team = this.teams.find((t) => t.id === teamId);
    if (!team) return;
    if (!Number.isFinite(budget)) return;
    // A budget below what the team already committed would leave it with
    // negative money to spend, so it cannot go under the amount already spent.
    team.budget = Math.max(team.spent, Math.round(budget));
    team.remaining = team.budget - team.spent;
  }

  getAuctionPlayers(): Player[] {
    return this.players;
  }

  getSnakeDraftPlayers(): SnakeDraftPlayer[] {
    // Return empty array since snake draft uses separate database
    return [];
  }
}
