// Auction draft engine. The player pool and every number attached to it are
// generated by scripts/build-player-pool.mjs from nflverse data; see CLAUDE.md.
import poolData from '@/data/nfl/pool.json';
import {
  DEFAULT_LEAGUE,
  leagueShape,
  normaliseLeague,
  pointsFor,
  pricePool,
  sameLeague,
  startingSlots,
  unfilledSlotsFor,
  type LeagueShape,
} from '@/lib/valuation';
import type { RankingOverride } from '@/lib/rankingsCsv';

interface PoolEntry {
  gsis: string;
  name: string;
  position: string;
  team: string;
  tier: number;
  rank: number;
  auctionValue: number;
  vorp: number;
  ceiling: number;
  floor: number;
  consistency: number;
  byeWeek: number | null;
  age: number | null;
  experience: number | null;
  lastSeasonGames: number | null;
  snapShare: number | null;
  targetShare: number | null;
  injuryRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  ageRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  role: 'LOCKED_STARTER' | 'MINOR_COMPETITION' | 'TIMESHARE' | 'COMMITTEE';
  trend: 'RISING' | 'STABLE' | 'DECLINING' | 'UNPROVEN';
  projection: {
    points: number;
    pointsPerGame: number;
    expectedGames: number;
    /** Projected catches. Absent on a pool built before scoring was configurable. */
    receptions?: number;
  };
  percentiles?: Record<string, number>;
  usage?: PlayerUsage | null;
  context?: TeamContext | null;
  durability?: Durability;
  competition?: DepthCompetition;
  market?: MarketRead;
  breakoutSeason?: number | null;
  draft?: { year: number; round: number; pick: number; team: string } | null;
  defense?: {
    sacks: number;
    interceptions: number;
    fumbleRecoveries: number;
    touchdowns: number;
    safeties: number;
    pointsAllowedPerGame: number | null;
  };
}

export interface Player {
  id: string;
  name: string;
  position: 'QB' | 'RB' | 'WR' | 'TE' | 'K' | 'DST';
  team: string;
  tier: 1 | 2 | 3 | 4;
  baseValue: number;
  estimatedValue: number;
  /**
   * What our own model says, kept even when an imported ranking has replaced
   * the value everything else reads. Facts and opinions stay distinguishable:
   * the board can show whose number it is showing.
   */
  modelValue: number;
  /** Present only when an imported ranking is overriding this player. */
  customRanking?: RankingOverride;
  /**
   * Whether the money is buying this player, or the snake is.
   *
   * The mask `pricePool` used, read back rather than derived again — which
   * players are for sale decides prices, what inflation is measured over and
   * when the auction is finished, and every one of those working it out
   * separately is a second definition that can disagree on the only night it
   * matters. It rides on the player object rather than arriving as a card
   * prop: the board mounts sixty memoised cards and a prop that changes with
   * the sheet would re-render all of them.
   *
   * True for everybody when the whole board is auctioned, because then there
   * is no sheet to be off.
   */
  onSheet: boolean;
  /**
   * Whether `onSheet` is a stated list or the model's guess at one.
   *
   * With a size typed into the settings panel but no list imported, the mask is
   * simply our own best N by surplus. Telling 568 players they are "not on the
   * auction sheet" is then stating as fact something nobody has said — and it
   * moves: removing a 60-name sheet leaves 60 players still marked, only 40 of
   * whom were ever on it. A guess and a fact have to read differently.
   */
  sheetIsStated: boolean;
  projectedPoints: number;
  adp: number; // Average Draft Position
  injuryRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  strengthOfSchedule?: number; // 1-10 scale
  valueOverReplacement: number; // VORP
  upside: number; // Ceiling projection
  floor: number; // Floor projection
  consistency: number; // Week-to-wave variance (1-10)
  byeWeek: number;
  ageRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  targetShare?: number; // Expected target/touch share %
  redZoneShare?: number; // Red zone opportunity %
  // Enhanced real data fields
  age?: number;
  experience?: number; // Years in NFL
  lastSeasonGames?: number;
  careerGames?: number;
  injuryHistory?: string[]; // List of past injuries
  contractStatus?: 'SECURE' | 'EXPIRING' | 'ROOKIE' | 'FRANCHISE_TAG';
  coachingStability?: 'STABLE' | 'NEW_COACH' | 'NEW_SYSTEM';
  offensiveLineRank?: number; // 1-32 team rank
  defensiveStrengthVsPosition?: number; // Opponent strength vs position
  weatherConcerns?: boolean; // Dome vs outdoor team
  playoffSchedule?: 'EASY' | 'MODERATE' | 'DIFFICULT';
  handcuffValue?: number; // Value if starter injured (0-100)
  primaryBackup?: string; // Name of primary backup
  competitionLevel: 'LOCKED_STARTER' | 'MINOR_COMPETITION' | 'TIMESHARE' | 'COMMITTEE';
  teamPaceRank?: number; // Team pace ranking (1-32)
  redZoneTouchesLastSeason?: number;
  snapPercentage?: number; // Expected snap %
  recentTrends: 'RISING' | 'STABLE' | 'DECLINING';
  fantasyRelevantWeeks?: number; // Weeks likely to be fantasy relevant
  floorWeeks?: number; // Number of weeks hitting floor
  ceilingWeeks?: number; // Number of weeks hitting ceiling
  /** Where each headline number sits among players at the same position, 0-100. */
  percentiles?: Record<string, number>;
  pointsPerGame?: number;
  expectedGames?: number;
  usage?: PlayerUsage | null;
  teamContext?: TeamContext | null;
  durability?: Durability;
  competition?: DepthCompetition;
  market?: MarketRead;
  breakoutSeason?: number | null;
  draftCapital?: { year: number; round: number; pick: number; team: string } | null;
  /** Team defense season totals. Present only for DST entries. */
  defense?: {
    sacks: number;
    interceptions: number;
    fumbleRecoveries: number;
    touchdowns: number;
    safeties: number;
    pointsAllowedPerGame: number | null;
  };
  isDrafted: boolean;
  draftedBy?: string;
  draftCost?: number;
  pickNumber?: number;
}

/** How a player's touches were earned, from the most recent season with a real
 *  sample. Volume is the projection; this is the shape of it. */
export interface PlayerUsage {
  season: number;
  games: number;
  targetShare: number | null;
  airYardsShare: number | null;
  wopr: number | null;
  adot: number | null;
  yacPerReception: number | null;
  carryShare: number | null;
  touchesPerGame: number | null;
  targetsPerGame: number | null;
  redZoneTouches: number;
  redZoneShare: number | null;
  goalLineTouches: number;
  firstDownsPerGame: number | null;
  epaPerTouch: number | null;
  passingEpa: number | null;
}

/** The offence a player lines up in. Opportunity is granted by a team before it
 *  is earned by a player. */
export interface TeamContext {
  playsPerGame: number;
  secondsPerPlay: number | null;
  neutralPassRate: number | null;
  passRateOverExpected: number | null;
  sackRateAllowed: number | null;
  epaPerPlay: number | null;
  redZoneTripsPerGame: number;
}

export interface Durability {
  seasons: Array<{ season: number; missed: number }>;
  totalMissed: number;
  /** Weeks on the injury report by body part — treatment, not absences. */
  reported: Array<{ part: string; weeks: number }>;
}

export interface DepthCompetition {
  depth: number;
  roomSize: number;
  aheadBy: number | null;
  behindBy: number | null;
  nextUp: string | null;
  starterAhead: string | null;
}

/** FantasyPros expert consensus, which ships its own disagreement. */
export interface MarketRead {
  consensusRank: number | null;
  positionRank: number | null;
  rawEcr: number | null;
  best: number | null;
  worst: number | null;
  spread: number | null;
  ownership: number | null;
  searchRank: number | null;
  depthChartOrder: number | null;
  source: string;
  asOf: string | null;
  /** Consensus rank minus our rank. Positive means the room is sleeping on him. */
  edge: number | null;
}

export type PlayerPosition = 'QB' | 'RB' | 'WR' | 'TE' | 'K' | 'DST';

/** Roster counts by position. Every draftable position needs a key here — a
 *  missing one turns `roster[position]++` into NaN and poisons depth scoring. */
export type RosterCounts = Record<PlayerPosition, number>;

export interface BidRejection {
  ok: false;
  /** Machine-readable so the UI can decide how loudly to complain. */
  code:
    | 'unknown-player'
    | 'unknown-team'
    | 'already-drafted'
    | 'invalid-amount'
    | 'insufficient-funds'
    | 'roster-full'
    | 'position-full';
  message: string;
}

export type BidCheck = { ok: true } | BidRejection;

export interface Team {
  id: string;
  name: string;
  budget: number;
  spent: number;
  remaining: number;
  roster: RosterCounts;
  projectedTotal: number;
  strengthScore: number;
  riskScore: number;
  depthScore: number;
  injuryInsurance: number;
}

export interface DraftAnalytics {
  baseValue: number;
  adjustedValue: number;
  maxBid: number;
  openingBid: number;
  targetBid: number;
  walkAwayPoint: number;
  needMultiplier: number;
  scarcityFactor: number;
  confidenceLevel: number;
  marketInflation: number;
  regressionRisk?: number;
  breakoutPotential?: number;
  positionScarcity: number;
  valueOverBaseline: number;
  riskAdjustedValue: number;
  optimalBidRange: [number, number];
  // Enhanced analytics
  injuryAdjustment: number;
  ageAdjustment: number;
  contractSecurityScore?: number;
  coachingStabilityScore?: number;
  teamEnvironmentScore?: number;
  competitionRisk: number;
  handcuffRecommendation?: string;
  backupTargets?: string[];
  idealDraftPosition?: string;
  rosterId: string;
}

/** What the room is doing with its money, derived entirely from the pick log. */
export interface MarketState {
  inflation: number;
  premium: number | null;
  moneyLeft: number;
  valueLeft: number;
  scarcity: Array<{
    position: PlayerPosition;
    gone: number;
    total: number;
    tierOneLeft: number;
    /** What the room paid against our list at this position, once two have sold. */
    premium: number | null;
    sold: number;
    /** Points between the best player left here and the fifth: the cost of waiting. */
    cliff: number;
  }>;
}

export interface DraftState {
  players: Player[];
  teams: Team[];
  draftedCount: number;
  totalPlayers: number;
  currentPick: number;
}

export interface SnakeDraftPlayer {
  id: string;
  name: string;
  position: 'QB' | 'RB' | 'WR' | 'TE' | 'K' | 'DST';
  team: string;
  tier: 1 | 2 | 3 | 4 | 5;
  baseValue: number;
  estimatedValue: number;
  projectedPoints: number;
  adp: number;
  injuryRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  strengthOfSchedule: number;
  valueOverReplacement: number;
  upside: number;
  floor: number;
  consistency: number;
  byeWeek: number;
  ageRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  targetShare: number;
  redZoneShare: number;
  age: number;
  experience: number;
  lastSeasonGames: number;
  careerGames: number;
  injuryHistory: string[];
  contractStatus: 'SECURE' | 'EXPIRING' | 'ROOKIE' | 'FRANCHISE_TAG';
  coachingStability: 'STABLE' | 'NEW_COACH' | 'NEW_SYSTEM';
  offensiveLineRank: number;
  defensiveStrengthVsPosition: number;
  weatherConcerns: boolean;
  playoffSchedule: 'EASY' | 'MODERATE' | 'DIFFICULT';
  handcuffValue: number;
  primaryBackup?: string;
  competitionLevel: 'LOCKED_STARTER' | 'MINOR_COMPETITION' | 'TIMESHARE' | 'COMMITTEE';
  teamPaceRank: number;
  redZoneTouchesLastSeason: number;
  snapPercentage: number;
  recentTrends: 'RISING' | 'STABLE' | 'DECLINING';
  fantasyRelevantWeeks: number;
  floorWeeks: number;
  ceilingWeeks: number;
  // Enhanced snake draft specific analytics
  breakoutPotential: number;
  regressionRisk: number;
  rookieProjection?: number;
  coachingFit: number;
  opportunityRank: number;
  depthChart: number;
  sleeper: boolean;
  bustRisk: number;
  weeklyVolatility: number;
  positionalScarcity: number;
  handcuffRecommendation: string;
  isDrafted: boolean;
  draftedBy?: string;
  pickNumber?: number;
}

/**
 * The league the shipped pool was priced for.
 *
 * Read from pool.json rather than restated, so that regenerating the pool for a
 * different shape moves the client's default with it. Everything downstream
 * reads `this.league`, which starts here and can be changed at runtime.
 */
const POOL_LEAGUE: LeagueShape = leagueShape(
  (poolData as { league?: Partial<LeagueShape> }).league ?? DEFAULT_LEAGUE
);

/**
 * The chosen league, kept apart from the pick log.
 *
 * It is a league-wide fact rather than a per-person preference, so it does not
 * belong in `use-draft-preferences`; but it is also not a pick, and the pick
 * log deliberately stores nothing derived. Its own key keeps both rules intact.
 */
const LEAGUE_STORAGE_KEY = 'draft-vault:league:v1';

const readStoredLeague = (): LeagueShape => {
  try {
    const raw = localStorage.getItem(LEAGUE_STORAGE_KEY);
    if (!raw) return POOL_LEAGUE;
    return normaliseLeague(leagueShape(JSON.parse(raw) as Partial<LeagueShape>));
  } catch {
    // Unparseable or unavailable storage falls back to the league the pool was
    // priced for, which is always a valid one.
    return POOL_LEAGUE;
  }
};

const writeStoredLeague = (league: LeagueShape): void => {
  try {
    if (sameLeague(league, POOL_LEAGUE)) localStorage.removeItem(LEAGUE_STORAGE_KEY);
    else localStorage.setItem(LEAGUE_STORAGE_KEY, JSON.stringify(league));
  } catch {
    /* storage unavailable — the league simply won't be remembered */
  }
};

/**
 * Somebody else's rankings, laid over ours.
 *
 * An import is an opinion — the whole point of it is to disagree with the
 * model — so it is stored apart from both the pick log and the league, and the
 * model's own number survives underneath it on every player.
 */
const RANKINGS_STORAGE_KEY = 'draft-vault:custom-rankings:v1';

/**
 * The commissioner's sheet: which players the money is actually buying.
 *
 * A sheet *size* is a guess at this list — the best N by surplus, as though the
 * commissioner had picked ours. He picked off consensus rankings, so a player
 * we price at $2 is on it and a player we price at $30 is not. Kept in its own
 * key for the same reason the league is: it is a league-wide fact rather than a
 * per-person preference, and it is not a pick, so it cannot live in the pick
 * log — which stores nothing derived.
 *
 * `unsold` is the sheet player nobody bid a dollar on. He is marked rather than
 * struck off, because striking him off would shorten the sheet, and the sheet's
 * length is the league's `auctionSheetSize` — re-pricing the board mid-auction
 * and, since `sameLeague` is what lets a saved draft replay, refusing to
 * restore the draft being played.
 */
const SHEET_STORAGE_KEY = 'draft-vault:auction-sheet:v1';

/** The sheet as it is stored: who is being auctioned, and who went unsold. */
export interface StoredSheet {
  ids: string[];
  unsold: string[];
  /**
   * What `auctionSheetSize` was before the sheet pinned it.
   *
   * Removing a sheet has to put the league back where it found it, and nothing
   * else records that. Without it, applying a 60-name list to the default whole
   * board and then removing it leaves a permanent 60-player partial auction
   * nobody chose — the top of the board roughly doubles, 568 players sit at $1
   * wearing a snake badge, and the only way out is a league change that throws
   * the draft away.
   */
  priorSize?: number | null;
}

const EMPTY_SHEET = (): StoredSheet => ({ ids: [], unsold: [] });

const readStoredSheet = (): StoredSheet => {
  try {
    const raw = localStorage.getItem(SHEET_STORAGE_KEY);
    const parsed = raw ? (JSON.parse(raw) as Partial<StoredSheet>) : null;
    if (!parsed || !Array.isArray(parsed.ids)) return EMPTY_SHEET();
    return {
      ids: parsed.ids.filter((id): id is string => typeof id === 'string'),
      unsold: Array.isArray(parsed.unsold)
        ? parsed.unsold.filter((id): id is string => typeof id === 'string')
        : [],
      priorSize: typeof parsed.priorSize === 'number' ? parsed.priorSize : null,
    };
  } catch {
    return EMPTY_SHEET();
  }
};

const writeStoredSheet = (sheet: StoredSheet): void => {
  try {
    if (!sheet.ids.length) localStorage.removeItem(SHEET_STORAGE_KEY);
    else localStorage.setItem(SHEET_STORAGE_KEY, JSON.stringify(sheet));
  } catch {
    /* storage unavailable — the sheet simply won't survive a reload */
  }
};

/**
 * The draft a reset threw away.
 *
 * Reset sits next to Undo in the toolbar and used to be one unrecoverable
 * click: the pick log was deleted outright. Since the pick log is the only
 * shared fact, keeping the last one aside makes a reset undoable — which
 * matters most on the night, when the draft in progress is the only copy of an
 * afternoon's work.
 */
const CLEARED_STORAGE_KEY = 'draft-vault:cleared-draft:v1';

/**
 * Who the other eleven teams actually are.
 *
 * Deliberately not part of `LeagueShape`: that is the set of facts prices are
 * derived from, and `sameLeague` compares it to decide whether a draft can
 * survive a change. Renaming a team changes nothing about what a player is
 * worth, so putting names in there would throw the draft away over a typo.
 */
const ROSTER_STORAGE_KEY = 'draft-vault:teams:v1';

interface StoredTeams {
  names?: Record<string, string>;
  /** Which team is the person using this app. */
  mine?: string | null;
}

const readStoredTeams = (): StoredTeams => {
  try {
    const raw = localStorage.getItem(ROSTER_STORAGE_KEY);
    const parsed = raw ? (JSON.parse(raw) as StoredTeams) : null;
    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    return {};
  }
};

const writeStoredTeams = (value: StoredTeams): void => {
  try {
    if (!Object.keys(value.names ?? {}).length && !value.mine) {
      localStorage.removeItem(ROSTER_STORAGE_KEY);
    } else {
      localStorage.setItem(ROSTER_STORAGE_KEY, JSON.stringify(value));
    }
  } catch {
    /* storage unavailable — names simply will not be remembered */
  }
};

const readStoredOverrides = (): Record<string, RankingOverride> => {
  try {
    const raw = localStorage.getItem(RANKINGS_STORAGE_KEY);
    const parsed = raw ? (JSON.parse(raw) as Record<string, RankingOverride>) : null;
    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    return {};
  }
};

const writeStoredOverrides = (overrides: Record<string, RankingOverride>): void => {
  try {
    if (!Object.keys(overrides).length) localStorage.removeItem(RANKINGS_STORAGE_KEY);
    else localStorage.setItem(RANKINGS_STORAGE_KEY, JSON.stringify(overrides));
  } catch {
    /* storage unavailable — the import simply won't survive a reload */
  }
};

const EMPTY_ROSTER = (): RosterCounts => ({ QB: 0, RB: 0, WR: 0, TE: 0, K: 0, DST: 0 });

const rosterSize = (roster: RosterCounts): number =>
  Object.values(roster).reduce((total, count) => total + count, 0);

export class AuctionDraftService {
  private players: Player[] = [];
  private teams: Team[] = [];
  private draftedCount = 0;
  /** Pick order, so the last one can be taken back. */
  private history: Array<{ playerId: string; teamId: string; cost: number }> = [];
  /**
   * The league being drafted. Every rule and every dollar value derives from
   * it, so changing it re-prices the board rather than merely relabelling it.
   */
  private league: LeagueShape = POOL_LEAGUE;
  /** Replacement points per position under the active league. */
  private replacement: Record<string, number> = {};
  /**
   * Slots the reserve has to hold a dollar back for.
   *
   * A bid is capped at the budget minus a dollar for each of these, so that a
   * team cannot spend itself into a lineup it is unable to finish filling.
   *
   * That rule only holds when every roster spot has to be *bought*. In a
   * partial auction it is wrong, and wrong in the expensive direction: this
   * league auctions a commissioner's sheet of the best 50-100 players and fills
   * every remaining spot by snake draft, for free, with no minimum number a
   * team has to buy. A manager may legally put the whole $200 on three players
   * and snake the other thirteen. Holding $8 back for slots the snake will fill
   * caps our own bids below what the rules allow, and — worse — makes the room
   * read as poorer than it is, so an opponent looks tapped out at $88 when they
   * can still go to $96. Every bid we walk away from on that basis is a player
   * we lose while holding money we were never required to hold.
   *
   * So the reserve exists exactly when the auction covers the whole roster.
   *
   * The full-auction figure stays capped at the roster size: a league that
   * fields more players than it may roster is refused by the settings panel,
   * but if one ever reached the engine the reserve would exceed every budget
   * and no bid could be legal.
   */
  private get reservedSlots(): number {
    if (this.league.auctionSheetSize !== null) return 0;
    return Math.min(this.league.rosterSize, startingSlots(this.league));
  }
  /** Imported rankings, by player id. Empty unless somebody has imported some. */
  private overrides: Record<string, RankingOverride> = readStoredOverrides();
  /** The commissioner's sheet, if one has been imported. Empty ids means none. */
  private sheet: StoredSheet = readStoredSheet();
  /** Told after every change that reached storage, so other windows can follow. */
  private listeners = new Set<() => void>();
  /**
   * True while rebuilding from a change another window made.
   *
   * Replaying a saved draft writes to storage on every pick, so without this
   * the rebuild would announce itself back and the two windows would rebuild
   * each other in a loop.
   */
  private applyingRemote = false;
  /** Names people actually answer to, over the default "Team 3". */
  private teamNames: Record<string, string> = {};
  /** Which team belongs to the person running this. */
  private myTeamId: string | null = null;

  constructor(league: LeagueShape = readStoredLeague()) {
    this.league = normaliseLeague(league);
    const stored = readStoredTeams();
    this.teamNames = stored.names ?? {};
    this.myTeamId = stored.mine ?? null;
    this.initializePlayers();
    this.initializeTeams();
  }

  /**
   * The pool is generated, not typed by hand: scripts/build-player-pool.mjs
   * derives it from nflverse rosters and production, and every field below
   * traces back to a real observation or to the documented projection model.
   */
  private initializePlayers(): void {
    const entries = poolData.players as PoolEntry[];
    const mask = this.sheetMask(entries);

    // The pool ships values for the league it was built for. Rather than trust
    // them, re-derive from projected points — which are league-independent —
    // through the same module the builder used. At the default shape this
    // reproduces the stored numbers exactly (there is a test that says so),
    // and at any other shape it is the only way they could be right.
    const {
      replacement,
      priced,
      onSheet: bought,
    } = pricePool(
      entries.map((entry) => ({
        position: entry.position,
        points: entry.projection.points,
        receptions: entry.projection.receptions,
      })),
      this.league,
      mask ? { onSheet: mask } : {}
    );
    this.replacement = replacement;

    /*
     * Who the money bought is read back off the pricing, never worked out a
     * second time here — that is the whole reason pricePool returns the mask.
     *
     * The exception is a full auction, where there is no sheet to be off. The
     * mask is then simply the best 192 by surplus, and marking the rest
     * snake-only would state a fact about a format this league is not playing.
     */
    const wholeBoard = this.league.auctionSheetSize === null && !mask;

    this.players = entries.map((entry, index) =>
      this.buildPlayer(entry, priced[index], wholeBoard || bought[index], mask !== undefined)
    );
  }

  /**
   * The stored sheet as a mask over the pool, parallel to `entries`.
   *
   * Undefined when there is no sheet, which is what leaves `pricePool` to fall
   * back to `auctionSheetSize`. A sheet naming nobody in the pool — a file kept
   * across a pool rebuild — is also undefined rather than an auction of no
   * players, which would price all 628 at a dollar and lose the board.
   */
  /**
   * Whether this player is one the money is chasing.
   *
   * Five places asked `estimatedValue > 1` and meant this. The proxy holds only
   * while nothing overrides a price — and importing custom rankings, a shipped
   * feature, sets a value on whoever the importer ranked, including players the
   * commissioner left off the sheet. Those snake-only players then re-enter the
   * inflation denominator, so the room is told prices are softer than they are
   * for the rest of the night, and the bargain board starts recommending players
   * nobody is auctioning.
   *
   * The mask `pricePool` returned is the one answer. Nothing derives it again.
   */
  private forSale(player: Player): boolean {
    return player.onSheet && player.estimatedValue > 1;
  }

  private sheetMask(entries: PoolEntry[]): boolean[] | undefined {
    if (!this.sheet.ids.length) return undefined;
    const wanted = new Set(this.sheet.ids);
    // Anybody already sold was, by definition, bought with money, so he belongs
    // on the sheet whatever the pasted list says. Sheets arrive late and arrive
    // incomplete — pasted after bidding has started, or with a row that came
    // back ambiguous — and without this a player sold for $55 is re-priced at $1
    // the moment the list lands. His grade becomes a D, and every drafted player
    // is summed at his post-import dollar, so the room is told it is paying a
    // 29% premium on evidence that is entirely an artefact of the import.
    const sold = new Set(
      this.players.filter((player) => player.isDrafted).map((player) => player.id)
    );
    const mask = entries.map((entry) => wanted.has(entry.gsis) || sold.has(entry.gsis));
    return mask.some(Boolean) ? mask : undefined;
  }

  /**
   * One pool entry, priced for this league and then overlaid with any imported
   * ranking. The model's number stays on `modelValue` either way, so nothing
   * downstream has to choose between showing ours and showing theirs.
   */
  private buildPlayer(
    entry: PoolEntry,
    priced: { vorp: number; auctionValue: number },
    onSheet: boolean,
    sheetIsStated: boolean
  ): Player {
    const override = this.overrides[entry.gsis];
    const value = override?.value ?? priced.auctionValue;

    return {
      id: entry.gsis,
      name: entry.name,
      position: entry.position as PlayerPosition,
      team: entry.team,
      tier: (override?.tier ?? entry.tier) as 1 | 2 | 3 | 4,
      // Both follow the import: an opinion nobody's advice reflects is decoration.
      baseValue: value,
      estimatedValue: value,
      modelValue: priced.auctionValue,
      customRanking: override,
      // What this league awards, not the full-PPR total the pool ships.
      projectedPoints: Math.round(
        pointsFor(
          {
            position: entry.position,
            points: entry.projection.points,
            receptions: entry.projection.receptions,
          },
          this.league
        )
      ),
      // Rank by our own valuation. It is not an average draft position and is
      // not labelled as one.
      adp: override?.rank ?? entry.rank,
      injuryRisk: entry.injuryRisk,
      valueOverReplacement: Math.round(priced.vorp),
      upside: entry.ceiling,
      floor: entry.floor,
      consistency: entry.consistency,
      byeWeek: entry.byeWeek ?? 0,
      ageRisk: entry.ageRisk,
      age: entry.age ?? undefined,
      experience: entry.experience ?? undefined,
      lastSeasonGames: entry.lastSeasonGames ?? undefined,
      competitionLevel: entry.role,
      snapPercentage: entry.snapShare ?? undefined,
      targetShare: entry.targetShare ?? undefined,
      recentTrends: entry.trend === 'UNPROVEN' ? 'STABLE' : entry.trend,
      percentiles: entry.percentiles,
      pointsPerGame:
        entry.projection.expectedGames > 0
          ? Math.round(
              (pointsFor(
                {
                  position: entry.position,
                  points: entry.projection.points,
                  receptions: entry.projection.receptions,
                },
                this.league
              ) /
                entry.projection.expectedGames) *
                10
            ) / 10
          : entry.projection.pointsPerGame,
      expectedGames: entry.projection.expectedGames,
      usage: entry.usage ?? null,
      teamContext: entry.context ?? null,
      durability: entry.durability,
      competition: entry.competition,
      market: entry.market,
      breakoutSeason: entry.breakoutSeason ?? null,
      draftCapital: entry.draft ?? null,
      defense: entry.defense,
      onSheet,
      sheetIsStated,
      isDrafted: false,
    };
  }

  private initializeTeams(): void {
    this.teams = Array.from({ length: this.league.teams }, (_, i) => ({
      id: `team-${i + 1}`,
      name: this.teamNames[`team-${i + 1}`] || `Team ${i + 1}`,
      budget: this.league.budget,
      spent: 0,
      remaining: this.league.budget,
      roster: EMPTY_ROSTER(),
      projectedTotal: 0,
      strengthScore: 0,
      riskScore: 0,
      depthScore: 0,
      injuryInsurance: 0,
    }));
  }

  /** A fresh array each call: callers compare references to detect changes. */
  getPlayers(): Player[] {
    return [...this.players];
  }

  getTeams(): Team[] {
    return [...this.teams];
  }

  getDraftState(): DraftState {
    return {
      players: [...this.players],
      teams: [...this.teams],
      draftedCount: this.draftedCount,
      totalPlayers: this.players.length,
      currentPick: this.draftedCount + 1,
    };
  }

  /**
   * Whether this bid is legal, and if not, why.
   *
   * Callers should run this before offering a bid so the reason can be shown;
   * draftPlayer enforces it again regardless.
   */
  validateBid(playerId: string, teamId: string, cost: number): BidCheck {
    const player = this.players.find((p) => p.id === playerId);
    if (!player)
      return { ok: false, code: 'unknown-player', message: 'That player is not in the pool.' };
    if (player.isDrafted) {
      const owner = this.teams.find((t) => t.id === player.draftedBy);
      return {
        ok: false,
        code: 'already-drafted',
        message: `${player.name} already went to ${owner?.name ?? 'another team'} for $${player.draftCost}.`,
      };
    }

    const team = this.teams.find((t) => t.id === teamId);
    if (!team) return { ok: false, code: 'unknown-team', message: 'Pick a team first.' };

    // NaN fails every comparison, so it has to be rejected explicitly or it
    // sails through the budget check and turns the team's money into NaN.
    if (!Number.isInteger(cost) || cost < 1) {
      return {
        ok: false,
        code: 'invalid-amount',
        message: 'A bid must be a whole dollar amount of $1 or more.',
      };
    }

    const room = this.checkRoster(player, team);
    if (!room.ok) return room;

    const { spendable, held } = this.spendableFor(team);
    if (cost > spendable) {
      return {
        ok: false,
        code: 'insufficient-funds',
        message:
          held > 0
            ? `${team.name} can spend $${Math.max(0, spendable)} — $${held} is held back for ${held} open starting spot${held === 1 ? '' : 's'}.`
            : `${team.name} only has $${team.remaining} left.`,
      };
    }

    return { ok: true };
  }

  /**
   * Whether this team has room for this player at all, money aside.
   *
   * Split out of validateBid because a pick that costs nothing still has to
   * pass it, and because the most-they-can-bid question needs the money half
   * on its own. Two callers reading one copy is the point: a roster rule that
   * rejects a bid but not an identically illegal free pick is a rule in name
   * only.
   */
  private checkRoster(player: Player, team: Team): BidCheck {
    if (rosterSize(team.roster) >= this.league.rosterSize) {
      return {
        ok: false,
        code: 'roster-full',
        message: `${team.name} already has ${this.league.rosterSize} players.`,
      };
    }
    if (team.roster[player.position] >= this.league.positionLimits[player.position]) {
      return {
        ok: false,
        code: 'position-full',
        message: `${team.name} cannot carry more than ${this.league.positionLimits[player.position]} at ${player.position}.`,
      };
    }
    return { ok: true };
  }

  /**
   * The most this team may legally commit to one player, and what is withheld.
   *
   * The reserve is `reservedSlots` — zero whenever the snake fills the rest of
   * the roster for free. Anything that wants to state a team's ceiling has to
   * come through here rather than recomputing it, or the number shown beside a
   * bid box drifts from the number the engine will actually accept, and the
   * first anyone knows of it is a rejected bid at the worst moment.
   */
  private spendableFor(team: Team): { spendable: number; held: number } {
    const held = Math.max(0, this.reservedSlots - rosterSize(team.roster) - 1);
    return { spendable: team.remaining - held, held };
  }

  draftPlayer(playerId: string, teamId: string, cost: number): boolean {
    if (!this.validateBid(playerId, teamId, cost).ok) return false;

    const player = this.players.find((p) => p.id === playerId)!;
    const team = this.teams.find((t) => t.id === teamId)!;

    player.isDrafted = true;
    player.draftedBy = teamId;
    player.draftCost = cost;
    player.pickNumber = this.draftedCount + 1;

    team.spent += cost;
    team.remaining -= cost;
    team.roster[player.position]++;
    team.projectedTotal += player.projectedPoints;

    this.draftedCount++;
    this.history.push({ playerId, teamId, cost });
    this.updateTeamMetrics(team);
    this.persist();

    return true;
  }

  /** Takes back the most recent pick. Returns the undone pick, or null. */
  undoLastPick(): { player: Player; team: Team; cost: number } | null {
    const last = this.history.pop();
    if (!last) return null;

    const player = this.players.find((p) => p.id === last.playerId);
    const team = this.teams.find((t) => t.id === last.teamId);
    if (!player || !team) return null;

    player.isDrafted = false;
    delete player.draftedBy;
    delete player.draftCost;
    delete player.pickNumber;

    team.spent -= last.cost;
    team.remaining += last.cost;
    team.roster[player.position] = Math.max(0, team.roster[player.position] - 1);
    team.projectedTotal -= player.projectedPoints;

    this.draftedCount = Math.max(0, this.draftedCount - 1);
    this.updateTeamMetrics(team);
    this.persist();

    return { player, team, cost: last.cost };
  }

  /**
   * Whose turn it is to nominate.
   *
   * Derived from the number of picks made rather than stored, so it can never
   * drift out of step with the draft and needs nothing extra synchronised if
   * this ever runs on more than one screen.
   */
  /**
   * Whether this team can still add anybody.
   *
   * A full roster is the practical end of a team's draft: the reserve rules
   * guarantee it can always afford a dollar for each open slot, so money never
   * strands a team with room.
   */
  canDraft(team: Team): boolean {
    return rosterSize(team.roster) < this.league.rosterSize;
  }

  /** True once no team has room for another player. */
  isComplete(): boolean {
    return this.teams.length > 0 && this.teams.every((team) => !this.canDraft(team));
  }

  /**
   * Whose turn it is to nominate.
   *
   * Rotation is still derived from the pick count rather than stored, but it
   * steps over teams that are full — a team whose roster is finished does not
   * keep getting handed the nomination, and at the end of the draft nobody is.
   */
  getNominatingTeam(): Team | undefined {
    if (!this.teams.length) return undefined;
    const start = this.draftedCount % this.teams.length;
    for (let step = 0; step < this.teams.length; step++) {
      const team = this.teams[(start + step) % this.teams.length];
      if (this.canDraft(team)) return team;
    }
    return undefined;
  }

  /** Nomination order from here, starting with whoever is up. */
  getNominationOrder(count = 4): Team[] {
    return Array.from(
      { length: Math.min(count, this.teams.length) },
      (_, offset) => this.teams[(this.draftedCount + offset) % this.teams.length]
    );
  }

  /**
   * How the room is behaving, as numbers a bidder can act on.
   *
   * Inflation above 1 means more money is chasing less value than the list
   * prices assume, so everything left will go for more than it says on the tin.
   * The premium is what has actually happened so far: what the room paid
   * divided by what we said those players were worth.
   */
  getMarketState(): MarketState {
    const drafted = this.players.filter((p) => p.isDrafted);
    const spent = drafted.reduce((total, p) => total + (p.draftCost ?? 0), 0);
    const listed = drafted.reduce((total, p) => total + p.estimatedValue, 0);

    const positions: PlayerPosition[] = ['QB', 'RB', 'WR', 'TE', 'K', 'DST'];
    const scarcity = positions.map((position) => {
      const startable = this.players.filter((p) => p.position === position && this.forSale(p));
      const sold = drafted.filter((p) => p.position === position);
      const soldFor = sold.reduce((total, p) => total + (p.draftCost ?? 0), 0);
      const soldList = sold.reduce((total, p) => total + p.estimatedValue, 0);

      // The drop from the best player left to the fifth-best: how much it costs
      // to wait. A big cliff is why a position becomes urgent.
      const remaining = startable
        .filter((p) => !p.isDrafted)
        .sort((a, b) => b.projectedPoints - a.projectedPoints);
      const cliff =
        remaining.length > 4
          ? Math.round(remaining[0].projectedPoints - remaining[4].projectedPoints)
          : 0;

      return {
        position,
        gone: startable.filter((p) => p.isDrafted).length,
        total: startable.length,
        tierOneLeft: this.players.filter(
          (p) => p.position === position && p.tier === 1 && !p.isDrafted
        ).length,
        /** What the room paid for this position against our list, once two have sold. */
        premium: sold.length >= 2 && soldList > 0 ? soldFor / soldList : null,
        sold: sold.length,
        cliff,
      };
    });

    return {
      inflation: this.calculateMarketInflation(),
      premium: listed > 0 ? spent / listed : null,
      moneyLeft: this.teams.reduce((total, team) => total + team.remaining, 0),
      valueLeft: this.players
        .filter((p) => !p.isDrafted && this.forSale(p))
        .reduce((total, p) => total + p.estimatedValue, 0),
      scarcity,
    };
  }

  /**
   * Replacement level per position, straight from the generated pool.
   *
   * Deliberately read rather than recomputed: it falls out of the league shape
   * in scripts/build-player-pool.mjs, and a second definition here would be a
   * third copy of LEAGUE to keep in step.
   */
  getReplacementLevel(position: PlayerPosition): number | null {
    return this.replacement[position] ?? null;
  }

  /** The league in force. Every value on the board was priced for exactly this. */
  getLeagueShape(): LeagueShape {
    return {
      ...this.league,
      positionLimits: { ...this.league.positionLimits },
      rostered: { ...this.league.rostered },
    };
  }

  /** The league the shipped pool was generated for, for showing what changed. */
  getPoolLeagueShape(): LeagueShape {
    return {
      ...POOL_LEAGUE,
      positionLimits: { ...POOL_LEAGUE.positionLimits },
      rostered: { ...POOL_LEAGUE.rostered },
    };
  }

  /**
   * How many players the pool actually holds at each position.
   *
   * A league may roster more of a position than exist in the pool — 32 teams
   * want 53 quarterbacks and there are 40 — and `replacementLevels` then falls
   * back to the worst one rather than erroring, which understates that
   * position's values. Nothing about that is visible from the board, so the
   * settings panel says it before a league is applied.
   */
  getPoolDepth(): Record<string, number> {
    const depth: Record<string, number> = {};
    for (const player of this.players) {
      depth[player.position] = (depth[player.position] ?? 0) + 1;
    }
    return depth;
  }

  /**
   * Give a team the name its owner answers to.
   *
   * Only one person runs this app while eleven others bid, so "Team 7" is a
   * number to hold in your head at exactly the moment there is no room for it.
   * Names cost nothing about the valuation, so unlike a league change this
   * leaves the draft entirely alone.
   */
  renameTeam(teamId: string, name: string): void {
    const trimmed = name.trim().slice(0, 40);
    const team = this.teams.find((t) => t.id === teamId);
    if (!team) return;

    const index = this.teams.indexOf(team);
    if (trimmed) this.teamNames[teamId] = trimmed;
    else delete this.teamNames[teamId];
    team.name = trimmed || `Team ${index + 1}`;

    writeStoredTeams({ names: this.teamNames, mine: this.myTeamId });
    this.announce();
  }

  /** Which team is the person running this, if they have said. */
  getMyTeamId(): string | null {
    return this.myTeamId;
  }

  /**
   * Say which team is yours.
   *
   * The whole point of watching eleven other rosters is to know what they can
   * still do to you; that only means anything once the app knows which one is
   * not an opponent.
   */
  setMyTeam(teamId: string | null): void {
    this.myTeamId = teamId && this.teams.some((t) => t.id === teamId) ? teamId : null;
    writeStoredTeams({ names: this.teamNames, mine: this.myTeamId });
    this.announce();
  }

  /**
   * What a league shape would do to prices, without committing to it.
   *
   * The settings panel changes numbers whose effect is invisible until you
   * apply them and lose the draft. Showing what the best player would cost lets
   * a shape be dialled against what the room actually pays — which, for a
   * format the model has never seen, is better evidence than the model.
   */
  getPricePreview(league: LeagueShape): { top: number; median: number; bought: number } {
    const entries = poolData.players as PoolEntry[];
    const wanted = normaliseLeague(league);

    /*
     * The stored sheet counts here only while the shape being previewed
     * auctions exactly as many players as the sheet names.
     *
     * This method takes a *hypothetical* league — the one being typed into the
     * settings panel — and an explicit mask overrides `auctionSheetSize`
     * entirely. Hand the mask over unconditionally and dragging "Players
     * auctioned" would show the current sheet's prices at every value of the
     * field: the number would move and the preview would not, which is worse
     * than showing nothing. Equal lengths is the one case where the field and
     * the list are saying the same thing. Anywhere else the field is the
     * question being asked, and it is answered from the size alone, which is
     * what that field is for.
     */
    const mask = this.sheetMask(entries);
    const usingSheet = mask && wanted.auctionSheetSize === this.sheet.ids.length;

    const { priced } = pricePool(
      entries.map((entry) => ({
        position: entry.position,
        points: entry.projection.points,
        receptions: entry.projection.receptions,
      })),
      wanted,
      usingSheet ? { onSheet: mask } : {}
    );
    const sold = priced
      .map((entry) => entry.auctionValue)
      .filter((value) => value > 1)
      .sort((a, b) => b - a);
    return {
      top: sold[0] ?? 0,
      median: sold[Math.floor(sold.length / 2)] ?? 0,
      bought: sold.length,
    };
  }

  /** The imported rankings in force, by player id. */
  getCustomRankings(): Record<string, RankingOverride> {
    return { ...this.overrides };
  }

  /** How many players an import is currently speaking for. */
  getCustomRankingCount(): number {
    return Object.keys(this.overrides).length;
  }

  /**
   * Lay an imported ranking over the board.
   *
   * Unlike a league change this does not invalidate picks already made — the
   * money spent is still the money spent — so a draft in progress survives it.
   * Only what the remaining players are said to be worth moves.
   */
  setCustomRankings(overrides: Record<string, RankingOverride>): void {
    this.overrides = { ...overrides };
    writeStoredOverrides(this.overrides);
    this.repriceInPlace();
    this.announce();
  }

  /** Drop the import and go back to what the model says. */
  clearCustomRankings(): void {
    if (!Object.keys(this.overrides).length) return;
    this.overrides = {};
    writeStoredOverrides(this.overrides);
    this.repriceInPlace();
    this.announce();
  }

  // -------------------------------------------------------------------------
  // the commissioner's sheet
  //
  // A sheet size is our guess at the list; this is the list. It changes what
  // the money is buying, which changes every price on the board — but it
  // changes no rule, so unlike a league change a draft in progress survives it.
  // -------------------------------------------------------------------------

  /** The sheet in force: who is being auctioned, and who went unsold. */
  getAuctionSheet(): StoredSheet {
    return { ids: [...this.sheet.ids], unsold: [...this.sheet.unsold] };
  }

  /** How many players the imported sheet names. Zero when there is no sheet. */
  getSheetCount(): number {
    return this.sheet.ids.length;
  }

  /**
   * Apply the commissioner's actual sheet.
   *
   * This is an import, not a league change. A sheet touches no roster rule and
   * only ever loosens the reserve — which this format already holds at zero —
   * so every pick already made stays exactly as legal as it was, and the draft
   * in progress survives. That is the same reasoning a rankings import runs on.
   *
   * The league's `auctionSheetSize` is pinned to the length of the list,
   * because a size and a list are two statements of one fact and a board priced
   * off one while a panel reports the other cannot be read. `LeagueSettings`
   * makes that field read-only for the same reason.
   *
   * Moving the league is what makes the stashed draft need re-stamping below:
   * `clearedPickCount` and `restoreClearedDraft` both refuse a stash bid under
   * a different league, and that net exists because Reset once destroyed an
   * afternoon's work. Importing a list is not a reason to quietly cut it.
   *
   * Returns how many of the ids the pool actually knows.
   */
  setAuctionSheet(ids: readonly string[]): number {
    const known = new Set(this.players.map((player) => player.id));
    const wanted = [...new Set(ids)].filter((id) => known.has(id));
    if (!wanted.length || this.tooConcentrated(wanted)) return 0;

    const onSheet = new Set(wanted);
    this.sheet = {
      ids: wanted,
      unsold: this.sheet.unsold.filter((id) => onSheet.has(id)),
      // Only on the first sheet: replacing one sheet with another must not
      // forget the size the board had before any of them arrived.
      priorSize: this.sheet.ids.length ? this.sheet.priorSize : this.league.auctionSheetSize,
    };
    writeStoredSheet(this.sheet);

    this.league = normaliseLeague({ ...this.league, auctionSheetSize: wanted.length });
    writeStoredLeague(this.league);
    this.restampStored();
    this.repriceInPlace();
    // persist() deletes the saved draft when there are no picks, so an empty
    // board announces without writing: the re-stamp above is what a saved
    // draft nobody has resumed yet needs.
    if (this.history.length) this.persist();
    else this.announce();
    return wanted.length;
  }

  /**
   * The shortest sheet that still prices sanely.
   *
   * The whole budget chases whatever is on the sheet, so a short one prices the
   * top of the board above what any single team holds — measured at 12 teams and
   * $200: twelve names put the best player at $238, or 119% of a budget, which
   * `validateBid` must reject for every team in the league. The board would then
   * carry a headline number nobody can legally bid.
   *
   * This is not a hypothetical setting somebody types. It is reached by accident
   * through the paste box: a surname-first export, or a defence block written in
   * nicknames, resolves a fraction of its names, and a sixty-name sheet quietly
   * becomes eighteen. Refusing here is what makes the import panel say so
   * instead. `normaliseLeague` also clamps the size up to the team count, so
   * anything below that would leave the stored size and the stored list
   * disagreeing about how many players are being auctioned.
   */
  private tooConcentrated(ids: readonly string[]): boolean {
    return this.previewSheet(ids).top > this.maxBiddablePrice();
  }

  /**
   * The most a player can be listed at and still be buyable: a whole budget.
   *
   * The whole budget chases whatever is on the sheet, so a list that is too
   * short prices its best player above what any single team holds — twelve names
   * put him at 119% of a budget — and `validateBid` must then reject that number
   * for every team in the league. The board would carry a headline price nobody
   * could legally bid.
   *
   * The bound is the budget rather than the 55% the pool's own tests assert,
   * because those two are answering different questions. 55% is a sanity check
   * on the *model*, over the whole board it was fitted to. A commissioner's list
   * is not the whole board: thirty good players beside thirty dollar players is
   * a real sheet, and the money genuinely does concentrate on the thirty. That
   * is expensive, not broken. Unbiddable is broken.
   *
   * Reaching it is not a setting anybody types. It happens through the paste box,
   * when a surname-first export or a defence block written in nicknames resolves
   * a fraction of its names and sixty quietly becomes eighteen.
   */
  maxBiddablePrice(): number {
    return this.league.budget;
  }

  /**
   * Drop the list.
   *
   * What happens to `auctionSheetSize` depends on whether anything was bought
   * under it, and the two cases are genuinely different.
   *
   * With picks on the board the size stays where the sheet put it. Those bids
   * were accepted under a zero reserve, and restoring a whole-board auction
   * would bring the reserve back and make picks already taken retrospectively
   * illegal. The room still auctions that many players; we simply no longer
   * know which, so pricing falls back to the best N by surplus.
   *
   * With an empty board there are no such bids, so keeping the size would strand
   * the owner in a partial auction they never chose. Removing a sheet has to be
   * an undo.
   */
  clearAuctionSheet(): void {
    if (!this.sheet.ids.length) return;
    const { priorSize } = this.sheet;
    this.sheet = EMPTY_SHEET();
    writeStoredSheet(this.sheet);

    if (!this.history.length && priorSize !== undefined) {
      this.league = normaliseLeague({ ...this.league, auctionSheetSize: priorSize });
      writeStoredLeague(this.league);
      this.restampStored();
    }

    this.repriceInPlace();
    if (this.history.length) this.persist();
    else this.announce();
  }

  /**
   * A sheet player the room passed over: nobody bid even a dollar.
   *
   * Marked, never struck off. The snake phase decides the auction is finished
   * when every sheet player is gone, and one unsold player would otherwise hold
   * that condition false forever — stranding the app in an auction the room
   * left twenty minutes ago. Deleting him instead would shorten the sheet,
   * which moves `auctionSheetSize`, which re-prices everyone still for sale
   * mid-auction and makes the draft being played unreplayable. A marker settles
   * who is left without touching a price.
   */
  removeFromSheet(playerId: string): boolean {
    if (!this.sheet.ids.includes(playerId)) return false;
    if (this.sheet.unsold.includes(playerId)) return false;
    this.sheet = { ...this.sheet, unsold: [...this.sheet.unsold, playerId] };
    writeStoredSheet(this.sheet);
    this.announce();
    return true;
  }

  /** Put an unsold player back up: the room came back to him. */
  returnToSheet(playerId: string): boolean {
    if (!this.sheet.unsold.includes(playerId)) return false;
    this.sheet = { ...this.sheet, unsold: this.sheet.unsold.filter((id) => id !== playerId) };
    writeStoredSheet(this.sheet);
    this.announce();
    return true;
  }

  /**
   * Sheet players still to come: not sold, not passed over.
   *
   * Derived from the pick log and the sheet rather than counted anywhere, so it
   * cannot drift from either. This is the condition the snake phase begins on.
   */
  getSheetRemaining(): Player[] {
    if (!this.sheet.ids.length) return [];
    const unsold = new Set(this.sheet.unsold);
    const onSheet = new Set(this.sheet.ids);
    return this.players.filter(
      (player) => onSheet.has(player.id) && !player.isDrafted && !unsold.has(player.id)
    );
  }

  /**
   * What a sheet would do to the board, without committing to it.
   *
   * The import panel has to show the shift before it is applied: a sheet is the
   * largest single input to a price in this format, and a list that quietly
   * doubles what the top of the board costs should say so first. Facts only —
   * what each player costs now, and what he would cost then.
   */
  previewSheet(ids: readonly string[]): {
    top: number;
    median: number;
    bought: number;
    movers: Array<{ id: string; name: string; from: number; to: number }>;
  } {
    const entries = poolData.players as PoolEntry[];
    const wanted = new Set(ids);
    const mask = entries.map((entry) => wanted.has(entry.gsis));
    const size = mask.filter(Boolean).length;
    if (!size) return { top: 0, median: 0, bought: 0, movers: [] };

    const { priced } = pricePool(
      entries.map((entry) => ({
        position: entry.position,
        points: entry.projection.points,
        receptions: entry.projection.receptions,
      })),
      normaliseLeague({ ...this.league, auctionSheetSize: size }),
      { onSheet: mask }
    );

    const now = new Map(this.players.map((player) => [player.id, player.modelValue]));
    const movers = entries
      .map((entry, index) => ({
        id: entry.gsis,
        name: entry.name,
        from: now.get(entry.gsis) ?? 1,
        to: priced[index].auctionValue,
        on: mask[index],
      }))
      .filter((entry) => entry.on && entry.to !== entry.from)
      .sort((a, b) => b.to - b.from - (a.to - a.from))
      .slice(0, 5)
      .map(({ id, name, from, to }) => ({ id, name, from, to }));

    const sold = priced
      .map((entry) => entry.auctionValue)
      .filter((value) => value > 1)
      .sort((a, b) => b - a);

    return {
      top: sold[0] ?? 0,
      median: sold[Math.floor(sold.length / 2)] ?? 0,
      bought: sold.length,
      movers,
    };
  }

  /**
   * Re-stamp storage whose league differs *only* by the auction sheet size.
   *
   * A saved draft and the stash a reset left behind are both refused when their
   * stamp disagrees with the league in force, which is right: those bids bought
   * players at prices this league does not charge. A sheet import moves
   * `auctionSheetSize` and nothing else, so that refusal would throw away work
   * for no reason — hence the re-stamp.
   *
   * The condition is the whole point, and it was missing. Re-stamping whatever
   * is there rewrites stamps that were being *correctly* refused: reset a draft,
   * change the league from twelve teams to ten, import a sheet, and the stash is
   * silently re-stamped as a ten-team draft. Restoring it then replays picks at
   * budgets and prices they were never bid under, and drops the ones that no
   * longer fit without saying so. That stash is the undo-the-reset net added
   * after a real 192-pick draft caught Reset destroying an afternoon, and an
   * unrelated import must not be able to cut its only guard.
   */
  private restampStored(): void {
    for (const key of [AuctionDraftService.STORAGE_KEY, CLEARED_STORAGE_KEY]) {
      try {
        const raw = localStorage.getItem(key);
        if (!raw) continue;
        const saved = JSON.parse(raw) as Record<string, unknown>;
        if (!Array.isArray(saved.picks) || !saved.league) continue;

        // Everything but the sheet size has to already agree. Anything else is
        // a stamp that should go on being refused.
        const stamp = normaliseLeague(leagueShape(saved.league as Partial<LeagueShape>));
        const asIfResized = { ...stamp, auctionSheetSize: this.league.auctionSheetSize };
        if (!sameLeague(normaliseLeague(asIfResized), this.league)) continue;

        localStorage.setItem(key, JSON.stringify({ ...saved, league: this.league }));
      } catch {
        /* unreadable or unavailable — nothing to re-stamp */
      }
    }
  }

  /**
   * Rebuild the pool's valuations while keeping the draft that is under way.
   *
   * Rebuilding outright would drop who owns whom, so each player is rebuilt
   * from the pool and then has its draft state copied back on.
   */
  private repriceInPlace(): void {
    const state = new Map(
      this.players.map((player) => [
        player.id,
        {
          isDrafted: player.isDrafted,
          draftedBy: player.draftedBy,
          draftCost: player.draftCost,
          pickNumber: player.pickNumber,
        },
      ])
    );

    this.initializePlayers();

    for (const player of this.players) {
      const previous = state.get(player.id);
      if (!previous?.isDrafted) continue;
      player.isDrafted = true;
      player.draftedBy = previous.draftedBy;
      player.draftCost = previous.draftCost;
      player.pickNumber = previous.pickNumber;
    }
  }

  /**
   * Change the league, re-pricing the board.
   *
   * Every dollar value, replacement level and roster rule moves, so a draft in
   * progress cannot survive the change — its picks were made against prices
   * that no longer exist. The picks are cleared rather than silently
   * reinterpreted. Returns false when the shape would not change anything.
   */
  setLeagueShape(next: LeagueShape): boolean {
    const wanted = normaliseLeague(next);
    if (sameLeague(wanted, this.league)) return false;
    this.league = wanted;
    this.draftedCount = 0;
    this.history = [];
    this.initializePlayers();
    this.initializeTeams();
    writeStoredLeague(this.league);
    this.persist();
    return true;
  }

  /**
   * What a hypothetical purchase does to the rest of a roster.
   *
   * The number that actually decides a bid is not the price — it is what is left
   * per slot afterwards, and whether that still buys starters. This answers it
   * without committing anything.
   */
  simulateSpend(
    teamId: string,
    cost: number
  ): {
    remaining: number;
    slotsLeft: number;
    perSlot: number;
    /** Slots that must be filled at a dollar to stay legal. */
    minimumHold: number;
    /** True only when the amount is a real bid the reserve rules would allow. */
    /** Best player still on the board that the leftover budget could afford. */
    affordable: Player | null;
    legal: boolean;
  } | null {
    const team = this.teams.find((t) => t.id === teamId);
    if (!team) return null;

    const filled = Object.values(team.roster).reduce((a, b) => a + b, 0);
    const slotsLeft = Math.max(0, this.league.rosterSize - filled - 1);
    const remaining = team.remaining - cost;
    // Every unfilled starting slot still needs a dollar in reserve, exactly as
    // validateBid enforces it.
    const minimumHold = Math.max(0, this.reservedSlots - filled - 1);
    const spendable = remaining - minimumHold;
    const affordable =
      spendable > 0
        ? (this.players
            .filter((p) => !p.isDrafted && p.id !== undefined && p.estimatedValue <= spendable)
            .sort((a, b) => b.projectedPoints - a.projectedPoints)[0] ?? null)
        : null;

    return {
      remaining,
      slotsLeft,
      perSlot: slotsLeft > 0 ? Math.max(0, remaining - minimumHold) / slotsLeft : 0,
      minimumHold,
      affordable,
      legal: remaining >= minimumHold && cost >= 1,
    };
  }

  /**
   * Where our board and the market's disagree, in dollars.
   *
   * `market.edge` is a difference of ranks; this converts it into what it is
   * worth tonight by pricing each player at the room's current inflation. A
   * player the consensus ranks 40 spots below us is only a bargain if he is
   * still going to be cheap when he comes up.
   */
  getBargains(limit = 24): Array<{
    player: Player;
    edge: number;
    listed: number;
    projectedCost: number;
    saving: number;
  }> {
    const inflation = this.calculateMarketInflation();
    return this.players
      .filter((p) => !p.isDrafted && p.market?.consensusRank != null && this.forSale(p))
      .map((player) => {
        const listed = player.estimatedValue;
        // The room bids off consensus, so the expected price tracks the market
        // rank, not ours; inflation moves both.
        const projectedCost = Math.max(1, Math.round(listed * inflation));
        return {
          player,
          edge: player.market?.edge ?? 0,
          listed,
          projectedCost,
          saving: Math.round(listed - projectedCost + (player.market?.edge ?? 0) * 0.12),
        };
      })
      .sort((a, b) => b.edge - a.edge || b.listed - a.listed)
      .slice(0, limit);
  }

  /** Every pick so far, grouped for the league board. */
  getDraftBoard(): Array<{
    team: Team;
    picks: Array<{ player: Player; cost: number; pickNumber: number }>;
  }> {
    return this.teams.map((team) => ({
      team,
      picks: this.players
        .filter((p) => p.draftedBy === team.id)
        .map((p) => ({ player: p, cost: p.draftCost ?? 0, pickNumber: p.pickNumber ?? 0 }))
        .sort((a, b) => a.pickNumber - b.pickNumber),
    }));
  }

  canUndo(): boolean {
    return this.history.length > 0;
  }

  private updateTeamMetrics(team: Team): void {
    const teamPlayers = this.players.filter((p) => p.draftedBy === team.id);

    // Calculate strength score (average projected points)
    team.strengthScore =
      teamPlayers.length > 0
        ? teamPlayers.reduce((sum, p) => sum + p.projectedPoints, 0) / teamPlayers.length
        : 0;

    // Calculate risk score (average injury risk)
    const riskValues = { LOW: 1, MEDIUM: 2, HIGH: 3 };
    team.riskScore =
      teamPlayers.length > 0
        ? teamPlayers.reduce((sum, p) => sum + riskValues[p.injuryRisk], 0) / teamPlayers.length
        : 0;

    // Players beyond the starting lineup. This read from its own QB1/RB2/WR2
    // table, which disagreed with the QB1/RB2/WR3 one urgency used — a third
    // receiver counted as bench depth and as a starter at the same time.
    team.depthScore = Object.entries(team.roster).reduce((total, [pos, count]) => {
      const starting = this.league.startingLineup[pos as PlayerPosition] ?? 0;
      return total + Math.max(0, count - starting);
    }, 0);

    // Calculate injury insurance (handcuff value)
    team.injuryInsurance = teamPlayers.reduce((sum, p) => sum + (p.handcuffValue ?? 0), 0) / 100;
  }

  /**
   * What this player should cost this team, right now.
   *
   * Three real forces move a price away from the list value: how much money is
   * still chasing how much value (inflation), how badly this team still needs
   * the position (need), and how little of the position is left (scarcity).
   * Nothing here is invented — each one is read off the current draft state.
   */
  generateDraftAnalytics(playerId: string, teamId: string): DraftAnalytics {
    const player = this.players.find((p) => p.id === playerId);
    const team = this.teams.find((t) => t.id === teamId);
    if (!player || !team) throw new Error('Player or team not found');

    const marketInflation = this.calculateMarketInflation();
    const needMultiplier = this.calculateNeedMultiplier(player.position, team);
    const positionScarcity = this.calculatePositionScarcity(player.position);

    const adjustedValue =
      player.baseValue * marketInflation * needMultiplier * (1 + positionScarcity * 0.15);

    // Injury and age history discount what we are willing to commit.
    const riskFactor =
      (player.injuryRisk === 'HIGH' ? 0.88 : player.injuryRisk === 'MEDIUM' ? 0.95 : 1) *
      (player.ageRisk === 'HIGH' ? 0.9 : player.ageRisk === 'MEDIUM' ? 0.96 : 1);
    const riskAdjustedValue = adjustedValue * riskFactor;

    const filled = Object.values(team.roster).reduce((total, count) => total + count, 0);
    const slotsToFill = Math.max(0, this.reservedSlots - filled - 1);
    const spendable = Math.max(1, team.remaining - slotsToFill);

    const targetBid = Math.max(1, Math.round(riskAdjustedValue));
    const maxBid = Math.max(1, Math.min(Math.round(riskAdjustedValue * 1.15), spendable));
    const openingBid = Math.max(1, Math.round(targetBid * 0.6));

    return {
      baseValue: player.baseValue,
      adjustedValue: Math.round(adjustedValue),
      maxBid,
      openingBid,
      targetBid,
      // The first dollar you should not spend.
      walkAwayPoint: maxBid + 1,
      needMultiplier: Math.round(needMultiplier * 100) / 100,
      scarcityFactor: Math.round(positionScarcity * 100) / 100,
      confidenceLevel: this.calculateConfidenceLevel(player),
      marketInflation: Math.round(marketInflation * 100) / 100,
      positionScarcity: Math.round(positionScarcity * 100) / 100,
      valueOverBaseline: player.valueOverReplacement,
      riskAdjustedValue: Math.round(riskAdjustedValue),
      optimalBidRange: [openingBid, maxBid],
      injuryAdjustment: Math.round((1 - riskFactor) * 100) / 100,
      ageAdjustment: player.ageRisk === 'LOW' ? 0 : player.ageRisk === 'MEDIUM' ? 0.04 : 0.1,
      competitionRisk: player.competitionLevel === 'LOCKED_STARTER' ? 0 : 0.15,
      rosterId: team.id,
    };
  }

  /**
   * Dollars still available divided by the value still on the board. Above 1.0
   * the room is going to overpay for what is left; below it, bargains.
   */
  private calculateMarketInflation(): number {
    const openSlots = this.teams.reduce(
      (total, team) =>
        total +
        Math.max(0, this.reservedSlots - Object.values(team.roster).reduce((a, b) => a + b, 0)),
      0
    );
    const moneyLeft = this.teams.reduce((total, team) => total + team.remaining, 0) - openSlots;
    const valueLeft = this.players
      .filter((p) => !p.isDrafted && this.forSale(p))
      .reduce((total, p) => total + p.estimatedValue, 0);
    if (valueLeft <= 0) return 1;
    return Math.max(0.6, Math.min(1.8, moneyLeft / valueLeft));
  }

  /**
   * How urgently this team still needs the position.
   *
   * An empty slot early is not urgent — there is a whole draft left to fill it.
   * The premium therefore grows with how much of the position is already gone,
   * which is what actually makes a hole expensive.
   */
  private calculateNeedMultiplier(position: string, team: Team): number {
    // Derived from the league's own lineup, so a superflex or a 3-WR league
    // makes the positions it actually starts urgent, and a flex counts for
    // every position that could fill it.
    const unfilled = unfilledSlotsFor(position as PlayerPosition, team.roster, this.league);
    const gone = this.calculatePositionScarcity(position);
    return 1 + Math.min(0.45, unfilled * 0.18 * gone);
  }

  /** Share of the position's startable players already off the board. */
  private calculatePositionScarcity(position: string): number {
    const startable = this.players.filter((p) => p.position === position && this.forSale(p));
    if (!startable.length) return 0;
    const gone = startable.filter((p) => p.isDrafted).length;
    return gone / startable.length;
  }

  /** How much of this player we have actually seen, on a 0-100 scale. */
  private calculateConfidenceLevel(player: Player): number {
    const games = player.lastSeasonGames ?? 0;
    const sample = Math.min(1, games / 17);
    const steadiness = (player.consistency ?? 5) / 10;
    return Math.round((sample * 0.6 + steadiness * 0.4) * 100);
  }

  isDraftComplete(): boolean {
    return this.draftedCount >= 60;
  }

  searchPlayers(query: string): Player[] {
    if (!query) return this.players;
    return this.players.filter(
      (p) =>
        p.name.toLowerCase().includes(query.toLowerCase()) ||
        p.position.toLowerCase().includes(query.toLowerCase()) ||
        p.team.toLowerCase().includes(query.toLowerCase())
    );
  }

  getPlayerAnalytics(playerId: string, teamId: string = 'team-1'): DraftAnalytics {
    return this.generateDraftAnalytics(playerId, teamId);
  }

  getDraftedPlayers(): Player[] {
    return this.players.filter((p) => p.isDrafted);
  }

  getAvailablePlayers(): Player[] {
    return this.players.filter((p) => !p.isDrafted);
  }

  resetDraft(): void {
    // Stash before clearing, so the reset can be taken back.
    if (this.history.length) {
      try {
        localStorage.setItem(
          CLEARED_STORAGE_KEY,
          JSON.stringify({
            clearedAt: new Date().toISOString(),
            league: this.league,
            budgets: this.teams.map((t) => ({ id: t.id, budget: t.budget })),
            picks: this.history,
          })
        );
      } catch {
        /* storage unavailable — the reset is simply not undoable */
      }
    }

    this.players.forEach((p) => {
      p.isDrafted = false;
      delete p.draftedBy;
      delete p.draftCost;
      delete p.pickNumber;
    });
    this.draftedCount = 0;
    this.history = [];
    this.teams.forEach((team) => {
      team.spent = 0;
      team.remaining = team.budget;
      team.roster = EMPTY_ROSTER();
      team.projectedTotal = 0;
      // Derived metrics too: leaving these behind makes a reset draft report
      // the strength and risk of the roster it just threw away.
      team.strengthScore = 0;
      team.riskScore = 0;
      team.depthScore = 0;
      team.injuryInsurance = 0;
    });
    this.persist();
  }

  // -------------------------------------------------------------------------
  // persistence
  //
  // Only the picks are stored: replaying them rebuilds every derived number, so
  // a saved draft can never disagree with the current valuation logic.
  // -------------------------------------------------------------------------

  /**
   * Watch for changes that reached storage.
   *
   * Deliberately carries nothing: a listener is being told the draft moved, not
   * what it moved to. Whatever it needs, it reads back from the engine, which
   * is the same rule that keeps the pick log the only shared fact.
   */
  addChangeListener(listener: () => void): () => void {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }

  /**
   * The single-listener form, kept because one caller reads naturally as one.
   *
   * It cannot stay the only form: a second window follows the draft through
   * it already, and anything else that wants to react to a pick — a save, a
   * sync, a refresh — would silently take the slot and stop the first from
   * ever firing again. A Set is the seam; this is a convenience over it.
   */
  setChangeListener(listener: (() => void) | null): void {
    this.listeners.clear();
    if (listener) this.listeners.add(listener);
  }

  /**
   * Put a saved pick log back on the board, and say how much of it landed.
   *
   * Three callers replay — resuming this browser's draft, taking back a reset,
   * and loading a file — and they were three copies of the same loop. That is
   * one loop three chances to diverge, and a pick that replays differently
   * depending on which door it came through is a draft that disagrees with
   * itself. Picks that no longer validate are counted, never dropped quietly.
   */
  private replay(picks: ReadonlyArray<{ playerId: string; teamId: string; cost: number }>): number {
    let restored = 0;
    for (const pick of picks) {
      if (this.draftPlayer(pick.playerId, pick.teamId, pick.cost)) restored++;
    }
    return restored;
  }

  private announce(): void {
    if (this.applyingRemote) return;
    for (const listener of this.listeners) listener();
  }

  /**
   * Rebuild from what another window wrote.
   *
   * The whole state is re-derived from storage rather than patched, because a
   * patch would need to know what changed and the channel deliberately does not
   * say. Rebuilding cannot drift; a patch could.
   */
  reloadFromStorage(): void {
    this.applyingRemote = true;
    try {
      this.league = normaliseLeague(readStoredLeague());
      this.overrides = readStoredOverrides();
      // The sheet decides what the money is buying, so it has to be back in
      // hand before the board is priced rather than after it.
      this.sheet = readStoredSheet();
      const stored = readStoredTeams();
      this.teamNames = stored.names ?? {};
      this.myTeamId = stored.mine ?? null;
      this.draftedCount = 0;
      this.history = [];
      this.initializePlayers();
      this.initializeTeams();
      // Replays the pick log the other window just wrote. A cleared draft
      // leaves nothing to restore, which is the correct empty board.
      this.restore();
    } finally {
      this.applyingRemote = false;
    }
  }

  private persist(): void {
    try {
      // Emptying the draft is a change like any other. This used to `return`
      // here, which skipped the announcement below — so a second window
      // followed picks but never followed an undo back to zero, a reset, or a
      // league change (which clears the picks and so lands on this branch).
      if (!this.history.length) {
        localStorage.removeItem(AuctionDraftService.STORAGE_KEY);
      } else {
        localStorage.setItem(
          AuctionDraftService.STORAGE_KEY,
          JSON.stringify({
            version: 2,
            savedAt: new Date().toISOString(),
            // Stamped, not to be replayed from, but so a pick log cannot be
            // reinterpreted under a league it was never bid in. Absent on saves
            // written before leagues were configurable, which were all default.
            league: this.league,
            budgets: this.teams.map((t) => ({ id: t.id, budget: t.budget })),
            picks: this.history,
          })
        );
      }
    } catch {
      /* storage unavailable (private mode, quota) — the draft simply won't resume */
    }
    this.announce();
  }

  /** Replays a saved draft. Returns how many picks were restored. */
  restore(): number {
    let saved: {
      version?: number;
      league?: LeagueShape;
      budgets?: Array<{ id: string; budget: number }>;
      picks?: Array<{ playerId: string; teamId: string; cost: number }>;
    } | null = null;
    try {
      const raw = localStorage.getItem(AuctionDraftService.STORAGE_KEY);
      saved = raw ? JSON.parse(raw) : null;
    } catch {
      saved = null;
    }
    if (!saved?.picks?.length || saved.version !== 2) return 0;

    // Those bids bought players at prices this league does not charge. Replaying
    // them would produce a roster nobody could have afforded, so decline.
    const savedLeague = saved.league ? normaliseLeague(leagueShape(saved.league)) : POOL_LEAGUE;
    if (!sameLeague(savedLeague, this.league)) return 0;

    this.resetDraft();
    for (const { id, budget } of saved.budgets ?? []) this.updateTeamBudget(id, budget);

    const restored = this.replay(saved.picks);
    return restored;
  }

  /**
   * How many picks a reset threw away, if one can still be taken back.
   *
   * Only offered while the board is empty: once somebody drafts again the
   * cleared draft is genuinely history, and restoring it would silently
   * replace work done since.
   */
  clearedPickCount(): number {
    if (this.history.length) return 0;
    try {
      const raw = localStorage.getItem(CLEARED_STORAGE_KEY);
      const saved = raw ? (JSON.parse(raw) as { league?: LeagueShape; picks?: unknown[] }) : null;
      if (!saved?.picks?.length) return 0;
      // Prices moved on if the league changed; those bids no longer make sense.
      const league = saved.league ? normaliseLeague(leagueShape(saved.league)) : POOL_LEAGUE;
      return sameLeague(league, this.league) ? saved.picks.length : 0;
    } catch {
      return 0;
    }
  }

  /** Put back the draft the last reset cleared. Returns how many picks returned. */
  restoreClearedDraft(): number {
    if (this.history.length) return 0;
    let saved: {
      league?: LeagueShape;
      budgets?: Array<{ id: string; budget: number }>;
      picks?: Array<{ playerId: string; teamId: string; cost: number }>;
    } | null = null;
    try {
      const raw = localStorage.getItem(CLEARED_STORAGE_KEY);
      saved = raw ? JSON.parse(raw) : null;
    } catch {
      saved = null;
    }
    if (!saved?.picks?.length) return 0;

    const league = saved.league ? normaliseLeague(leagueShape(saved.league)) : POOL_LEAGUE;
    if (!sameLeague(league, this.league)) return 0;

    for (const { id, budget } of saved.budgets ?? []) this.updateTeamBudget(id, budget);
    const restored = this.replay(saved.picks);
    try {
      localStorage.removeItem(CLEARED_STORAGE_KEY);
    } catch {
      /* nothing to clean up */
    }
    return restored;
  }

  /**
   * The draft as a file somebody can keep.
   *
   * localStorage is one browser profile on one machine: a cleared cache, a
   * borrowed laptop or a dead battery loses the afternoon. This is the same
   * thing `persist()` writes, plus the league it was bid under, so a draft can
   * be carried somewhere else and picked up mid-auction.
   */
  exportDraft(): string {
    return JSON.stringify(
      {
        kind: 'draft-vault-draft',
        version: 1,
        savedAt: new Date().toISOString(),
        league: this.league,
        // The sheet travels beside the league because it is now part of what
        // set the prices: the same picks under the same league but a different
        // list describe a different auction. A draft carried to a backup laptop
        // has to price identically, not approximately.
        auctionSheet: this.sheet,
        // Who the teams are travels with the draft: a pick log full of
        // "Team 7" is a worse record of the night than it needs to be.
        teamNames: this.teamNames,
        myTeamId: this.myTeamId,
        budgets: this.teams.map((t) => ({ id: t.id, budget: t.budget })),
        picks: this.history,
      },
      null,
      2
    );
  }

  /**
   * Load a draft from a file, replacing whatever is on the board.
   *
   * The league travels with the picks and is adopted, because prices are
   * meaningless without it — a draft bid in a ten-team league does not describe
   * a roster anybody could buy in a twelve-team one. Picks that no longer
   * validate are counted rather than silently dropped.
   */
  importDraft(
    text: string
  ): { ok: true; restored: number; skipped: number } | { ok: false; reason: string } {
    let saved: {
      kind?: string;
      league?: LeagueShape;
      auctionSheet?: Partial<StoredSheet>;
      teamNames?: Record<string, string>;
      myTeamId?: string | null;
      budgets?: Array<{ id: string; budget: number }>;
      picks?: Array<{ playerId: string; teamId: string; cost: number }>;
    };
    try {
      saved = JSON.parse(text);
    } catch {
      return { ok: false, reason: 'That file is not a saved draft — it is not readable as JSON.' };
    }

    if (!saved || saved.kind !== 'draft-vault-draft') {
      return { ok: false, reason: 'That file was not saved by Draft Vault.' };
    }
    if (!Array.isArray(saved.picks)) {
      return { ok: false, reason: 'That draft file has no picks in it.' };
    }

    this.league = saved.league ? normaliseLeague(leagueShape(saved.league)) : this.league;
    writeStoredLeague(this.league);
    // A file with no sheet replaces the board with a board that has none: the
    // import replaces what is here rather than merging into it, and a stale
    // list left behind would price this draft as no draft was ever priced.
    this.sheet = Array.isArray(saved.auctionSheet?.ids)
      ? {
          ids: saved.auctionSheet.ids.filter((id): id is string => typeof id === 'string'),
          unsold: Array.isArray(saved.auctionSheet.unsold)
            ? saved.auctionSheet.unsold.filter((id): id is string => typeof id === 'string')
            : [],
        }
      : EMPTY_SHEET();
    writeStoredSheet(this.sheet);
    if (saved.teamNames) this.teamNames = saved.teamNames;
    if (saved.myTeamId !== undefined) this.myTeamId = saved.myTeamId;
    writeStoredTeams({ names: this.teamNames, mine: this.myTeamId });
    this.draftedCount = 0;
    this.history = [];
    this.initializePlayers();
    this.initializeTeams();

    for (const { id, budget } of saved.budgets ?? []) this.updateTeamBudget(id, budget);

    const restored = this.replay(saved.picks);
    this.persist();
    return { ok: true, restored, skipped: saved.picks.length - restored };
  }

  /** Whether a resumable draft is sitting in storage. */
  static hasSavedDraft(): boolean {
    try {
      return !!localStorage.getItem(AuctionDraftService.STORAGE_KEY);
    } catch {
      return false;
    }
  }

  private static readonly STORAGE_KEY = 'draft-vault:auction-draft:v2';

  getHistory(): ReadonlyArray<{ playerId: string; teamId: string; cost: number }> {
    return this.history;
  }

  getValueGrade(estimatedValue: number, actualCost: number): string {
    const ratio = actualCost / estimatedValue;
    if (ratio <= 0.8) return 'A+';
    if (ratio <= 0.9) return 'A';
    if (ratio <= 1.0) return 'B+';
    if (ratio <= 1.1) return 'B';
    if (ratio <= 1.2) return 'C';
    return 'D';
  }

  getProgressPercentage(): number {
    return (this.draftedCount / 60) * 100;
  }

  updateTeamBudget(teamId: string, budget: number): void {
    const team = this.teams.find((t) => t.id === teamId);
    if (!team) return;
    if (!Number.isFinite(budget)) return;
    // A budget below what the team already committed would leave it with
    // negative money to spend, so it cannot go under the amount already spent.
    team.budget = Math.max(team.spent, Math.round(budget));
    team.remaining = team.budget - team.spent;
  }

  getAuctionPlayers(): Player[] {
    return this.players;
  }

  getSnakeDraftPlayers(): SnakeDraftPlayer[] {
    // Return empty array since snake draft uses separate database
    return [];
  }
}
