// Auction draft engine. The player pool and every number attached to it are
// generated by scripts/build-player-pool.mjs from nflverse data; see CLAUDE.md.
import poolData from '@/data/nfl/pool.json';

interface PoolEntry {
  gsis: string;
  name: string;
  position: string;
  team: string;
  tier: number;
  rank: number;
  auctionValue: number;
  vorp: number;
  ceiling: number;
  floor: number;
  consistency: number;
  byeWeek: number | null;
  age: number | null;
  experience: number | null;
  lastSeasonGames: number | null;
  snapShare: number | null;
  targetShare: number | null;
  injuryRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  ageRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  role: 'LOCKED_STARTER' | 'MINOR_COMPETITION' | 'TIMESHARE' | 'COMMITTEE';
  trend: 'RISING' | 'STABLE' | 'DECLINING' | 'UNPROVEN';
  projection: { points: number; pointsPerGame: number; expectedGames: number };
  percentiles?: Record<string, number>;
  usage?: PlayerUsage | null;
  context?: TeamContext | null;
  durability?: Durability;
  competition?: DepthCompetition;
  market?: MarketRead;
  breakoutSeason?: number | null;
  draft?: { year: number; round: number; pick: number; team: string } | null;
  defense?: {
    sacks: number;
    interceptions: number;
    fumbleRecoveries: number;
    touchdowns: number;
    safeties: number;
    pointsAllowedPerGame: number | null;
  };
}

export interface Player {
  id: string;
  name: string;
  position: 'QB' | 'RB' | 'WR' | 'TE' | 'K' | 'DST';
  team: string;
  tier: 1 | 2 | 3 | 4;
  baseValue: number;
  estimatedValue: number;
  projectedPoints: number;
  adp: number; // Average Draft Position
  injuryRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  strengthOfSchedule?: number; // 1-10 scale
  valueOverReplacement: number; // VORP
  upside: number; // Ceiling projection
  floor: number; // Floor projection
  consistency: number; // Week-to-wave variance (1-10)
  byeWeek: number;
  ageRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  targetShare?: number; // Expected target/touch share %
  redZoneShare?: number; // Red zone opportunity %
  // Enhanced real data fields
  age?: number;
  experience?: number; // Years in NFL
  lastSeasonGames?: number;
  careerGames?: number;
  injuryHistory?: string[]; // List of past injuries
  contractStatus?: 'SECURE' | 'EXPIRING' | 'ROOKIE' | 'FRANCHISE_TAG';
  coachingStability?: 'STABLE' | 'NEW_COACH' | 'NEW_SYSTEM';
  offensiveLineRank?: number; // 1-32 team rank
  defensiveStrengthVsPosition?: number; // Opponent strength vs position
  weatherConcerns?: boolean; // Dome vs outdoor team
  playoffSchedule?: 'EASY' | 'MODERATE' | 'DIFFICULT';
  handcuffValue?: number; // Value if starter injured (0-100)
  primaryBackup?: string; // Name of primary backup
  competitionLevel: 'LOCKED_STARTER' | 'MINOR_COMPETITION' | 'TIMESHARE' | 'COMMITTEE';
  teamPaceRank?: number; // Team pace ranking (1-32)
  redZoneTouchesLastSeason?: number;
  snapPercentage?: number; // Expected snap %
  recentTrends: 'RISING' | 'STABLE' | 'DECLINING';
  fantasyRelevantWeeks?: number; // Weeks likely to be fantasy relevant
  floorWeeks?: number; // Number of weeks hitting floor
  ceilingWeeks?: number; // Number of weeks hitting ceiling
  /** Where each headline number sits among players at the same position, 0-100. */
  percentiles?: Record<string, number>;
  pointsPerGame?: number;
  expectedGames?: number;
  usage?: PlayerUsage | null;
  teamContext?: TeamContext | null;
  durability?: Durability;
  competition?: DepthCompetition;
  market?: MarketRead;
  breakoutSeason?: number | null;
  draftCapital?: { year: number; round: number; pick: number; team: string } | null;
  /** Team defense season totals. Present only for DST entries. */
  defense?: {
    sacks: number;
    interceptions: number;
    fumbleRecoveries: number;
    touchdowns: number;
    safeties: number;
    pointsAllowedPerGame: number | null;
  };
  isDrafted: boolean;
  draftedBy?: string;
  draftCost?: number;
  pickNumber?: number;
}

/** How a player's touches were earned, from the most recent season with a real
 *  sample. Volume is the projection; this is the shape of it. */
export interface PlayerUsage {
  season: number;
  games: number;
  targetShare: number | null;
  airYardsShare: number | null;
  wopr: number | null;
  adot: number | null;
  yacPerReception: number | null;
  carryShare: number | null;
  touchesPerGame: number | null;
  targetsPerGame: number | null;
  redZoneTouches: number;
  redZoneShare: number | null;
  goalLineTouches: number;
  firstDownsPerGame: number | null;
  epaPerTouch: number | null;
  passingEpa: number | null;
}

/** The offence a player lines up in. Opportunity is granted by a team before it
 *  is earned by a player. */
export interface TeamContext {
  playsPerGame: number;
  secondsPerPlay: number | null;
  neutralPassRate: number | null;
  passRateOverExpected: number | null;
  sackRateAllowed: number | null;
  epaPerPlay: number | null;
  redZoneTripsPerGame: number;
}

export interface Durability {
  seasons: Array<{ season: number; missed: number }>;
  totalMissed: number;
  /** Weeks on the injury report by body part — treatment, not absences. */
  reported: Array<{ part: string; weeks: number }>;
}

export interface DepthCompetition {
  depth: number;
  roomSize: number;
  aheadBy: number | null;
  behindBy: number | null;
  nextUp: string | null;
  starterAhead: string | null;
}

/** FantasyPros expert consensus, which ships its own disagreement. */
export interface MarketRead {
  consensusRank: number | null;
  positionRank: number | null;
  rawEcr: number | null;
  best: number | null;
  worst: number | null;
  spread: number | null;
  ownership: number | null;
  searchRank: number | null;
  depthChartOrder: number | null;
  source: string;
  asOf: string | null;
  /** Consensus rank minus our rank. Positive means the room is sleeping on him. */
  edge: number | null;
}

export type PlayerPosition = 'QB' | 'RB' | 'WR' | 'TE' | 'K' | 'DST';

/** Roster counts by position. Every draftable position needs a key here — a
 *  missing one turns `roster[position]++` into NaN and poisons depth scoring. */
export type RosterCounts = Record<PlayerPosition, number>;

export interface BidRejection {
  ok: false;
  /** Machine-readable so the UI can decide how loudly to complain. */
  code:
    | 'unknown-player'
    | 'unknown-team'
    | 'already-drafted'
    | 'invalid-amount'
    | 'insufficient-funds'
    | 'roster-full'
    | 'position-full';
  message: string;
}

export type BidCheck = { ok: true } | BidRejection;

export interface Team {
  id: string;
  name: string;
  budget: number;
  spent: number;
  remaining: number;
  roster: RosterCounts;
  projectedTotal: number;
  strengthScore: number;
  riskScore: number;
  depthScore: number;
  injuryInsurance: number;
}

export interface DraftAnalytics {
  baseValue: number;
  adjustedValue: number;
  maxBid: number;
  openingBid: number;
  targetBid: number;
  walkAwayPoint: number;
  needMultiplier: number;
  scarcityFactor: number;
  confidenceLevel: number;
  marketInflation: number;
  regressionRisk?: number;
  breakoutPotential?: number;
  positionScarcity: number;
  valueOverBaseline: number;
  riskAdjustedValue: number;
  optimalBidRange: [number, number];
  // Enhanced analytics
  injuryAdjustment: number;
  ageAdjustment: number;
  contractSecurityScore?: number;
  coachingStabilityScore?: number;
  teamEnvironmentScore?: number;
  competitionRisk: number;
  handcuffRecommendation?: string;
  backupTargets?: string[];
  idealDraftPosition?: string;
  rosterId: string;
}

/** What the room is doing with its money, derived entirely from the pick log. */
export interface MarketState {
  inflation: number;
  premium: number | null;
  moneyLeft: number;
  valueLeft: number;
  scarcity: Array<{
    position: PlayerPosition;
    gone: number;
    total: number;
    tierOneLeft: number;
    /** What the room paid against our list at this position, once two have sold. */
    premium: number | null;
    sold: number;
    /** Points between the best player left here and the fifth: the cost of waiting. */
    cliff: number;
  }>;
}

export interface DraftState {
  players: Player[];
  teams: Team[];
  draftedCount: number;
  totalPlayers: number;
  currentPick: number;
}

export interface SnakeDraftPlayer {
  id: string;
  name: string;
  position: 'QB' | 'RB' | 'WR' | 'TE' | 'K' | 'DST';
  team: string;
  tier: 1 | 2 | 3 | 4 | 5;
  baseValue: number;
  estimatedValue: number;
  projectedPoints: number;
  adp: number;
  injuryRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  strengthOfSchedule: number;
  valueOverReplacement: number;
  upside: number;
  floor: number;
  consistency: number;
  byeWeek: number;
  ageRisk: 'LOW' | 'MEDIUM' | 'HIGH';
  targetShare: number;
  redZoneShare: number;
  age: number;
  experience: number;
  lastSeasonGames: number;
  careerGames: number;
  injuryHistory: string[];
  contractStatus: 'SECURE' | 'EXPIRING' | 'ROOKIE' | 'FRANCHISE_TAG';
  coachingStability: 'STABLE' | 'NEW_COACH' | 'NEW_SYSTEM';
  offensiveLineRank: number;
  defensiveStrengthVsPosition: number;
  weatherConcerns: boolean;
  playoffSchedule: 'EASY' | 'MODERATE' | 'DIFFICULT';
  handcuffValue: number;
  primaryBackup?: string;
  competitionLevel: 'LOCKED_STARTER' | 'MINOR_COMPETITION' | 'TIMESHARE' | 'COMMITTEE';
  teamPaceRank: number;
  redZoneTouchesLastSeason: number;
  snapPercentage: number;
  recentTrends: 'RISING' | 'STABLE' | 'DECLINING';
  fantasyRelevantWeeks: number;
  floorWeeks: number;
  ceilingWeeks: number;
  // Enhanced snake draft specific analytics
  breakoutPotential: number;
  regressionRisk: number;
  rookieProjection?: number;
  coachingFit: number;
  opportunityRank: number;
  depthChart: number;
  sleeper: boolean;
  bustRisk: number;
  weeklyVolatility: number;
  positionalScarcity: number;
  handcuffRecommendation: string;
  isDrafted: boolean;
  draftedBy?: string;
  pickNumber?: number;
}

/** Most a single team may carry at each position. */
const POSITION_LIMITS: RosterCounts = { QB: 3, RB: 6, WR: 7, TE: 3, K: 2, DST: 2 };

/** Roster size bounds for a twelve-team auction. */
const MAX_ROSTER_SIZE = 16;
const STARTING_LINEUP_SIZE = 9;

const EMPTY_ROSTER = (): RosterCounts => ({ QB: 0, RB: 0, WR: 0, TE: 0, K: 0, DST: 0 });

const rosterSize = (roster: RosterCounts): number =>
  Object.values(roster).reduce((total, count) => total + count, 0);

export class AuctionDraftService {
  private players: Player[] = [];
  private teams: Team[] = [];
  private draftedCount = 0;
  /** Pick order, so the last one can be taken back. */
  private history: Array<{ playerId: string; teamId: string; cost: number }> = [];

  constructor() {
    this.initializePlayers();
    this.initializeTeams();
  }

  /**
   * The pool is generated, not typed by hand: scripts/build-player-pool.mjs
   * derives it from nflverse rosters and production, and every field below
   * traces back to a real observation or to the documented projection model.
   */
  private initializePlayers(): void {
    this.players = (poolData.players as PoolEntry[]).map((entry) => ({
      id: entry.gsis,
      name: entry.name,
      position: entry.position as PlayerPosition,
      team: entry.team,
      tier: entry.tier as 1 | 2 | 3 | 4,
      baseValue: entry.auctionValue,
      estimatedValue: entry.auctionValue,
      projectedPoints: Math.round(entry.projection.points),
      // Rank by our own valuation. It is not an average draft position and is
      // not labelled as one.
      adp: entry.rank,
      injuryRisk: entry.injuryRisk,
      valueOverReplacement: Math.round(entry.vorp),
      upside: entry.ceiling,
      floor: entry.floor,
      consistency: entry.consistency,
      byeWeek: entry.byeWeek ?? 0,
      ageRisk: entry.ageRisk,
      age: entry.age ?? undefined,
      experience: entry.experience ?? undefined,
      lastSeasonGames: entry.lastSeasonGames ?? undefined,
      competitionLevel: entry.role,
      snapPercentage: entry.snapShare ?? undefined,
      targetShare: entry.targetShare ?? undefined,
      recentTrends: entry.trend === 'UNPROVEN' ? 'STABLE' : entry.trend,
      percentiles: entry.percentiles,
      pointsPerGame: entry.projection.pointsPerGame,
      expectedGames: entry.projection.expectedGames,
      usage: entry.usage ?? null,
      teamContext: entry.context ?? null,
      durability: entry.durability,
      competition: entry.competition,
      market: entry.market,
      breakoutSeason: entry.breakoutSeason ?? null,
      draftCapital: entry.draft ?? null,
      defense: entry.defense,
      isDrafted: false,
    }));
  }

  private initializeTeams(): void {
    this.teams = Array.from({ length: 12 }, (_, i) => ({
      id: `team-${i + 1}`,
      name: `Team ${i + 1}`,
      budget: 200,
      spent: 0,
      remaining: 200,
      roster: EMPTY_ROSTER(),
      projectedTotal: 0,
      strengthScore: 0,
      riskScore: 0,
      depthScore: 0,
      injuryInsurance: 0,
    }));
  }

  /** A fresh array each call: callers compare references to detect changes. */
  getPlayers(): Player[] {
    return [...this.players];
  }

  getTeams(): Team[] {
    return [...this.teams];
  }

  getDraftState(): DraftState {
    return {
      players: [...this.players],
      teams: [...this.teams],
      draftedCount: this.draftedCount,
      totalPlayers: this.players.length,
      currentPick: this.draftedCount + 1,
    };
  }

  /**
   * Whether this bid is legal, and if not, why.
   *
   * Callers should run this before offering a bid so the reason can be shown;
   * draftPlayer enforces it again regardless.
   */
  validateBid(playerId: string, teamId: string, cost: number): BidCheck {
    const player = this.players.find((p) => p.id === playerId);
    if (!player)
      return { ok: false, code: 'unknown-player', message: 'That player is not in the pool.' };
    if (player.isDrafted) {
      const owner = this.teams.find((t) => t.id === player.draftedBy);
      return {
        ok: false,
        code: 'already-drafted',
        message: `${player.name} already went to ${owner?.name ?? 'another team'} for $${player.draftCost}.`,
      };
    }

    const team = this.teams.find((t) => t.id === teamId);
    if (!team) return { ok: false, code: 'unknown-team', message: 'Pick a team first.' };

    // NaN fails every comparison, so it has to be rejected explicitly or it
    // sails through the budget check and turns the team's money into NaN.
    if (!Number.isInteger(cost) || cost < 1) {
      return {
        ok: false,
        code: 'invalid-amount',
        message: 'A bid must be a whole dollar amount of $1 or more.',
      };
    }

    const filled = rosterSize(team.roster);
    if (filled >= MAX_ROSTER_SIZE) {
      return {
        ok: false,
        code: 'roster-full',
        message: `${team.name} already has ${MAX_ROSTER_SIZE} players.`,
      };
    }
    if (team.roster[player.position] >= POSITION_LIMITS[player.position]) {
      return {
        ok: false,
        code: 'position-full',
        message: `${team.name} cannot carry more than ${POSITION_LIMITS[player.position]} at ${player.position}.`,
      };
    }

    // Every remaining starting slot still needs at least a dollar to fill.
    const slotsToFill = Math.max(0, STARTING_LINEUP_SIZE - filled - 1);
    const spendable = team.remaining - slotsToFill;
    if (cost > spendable) {
      return {
        ok: false,
        code: 'insufficient-funds',
        message:
          slotsToFill > 0
            ? `${team.name} can spend $${Math.max(0, spendable)} — $${slotsToFill} is held back for ${slotsToFill} open starting spot${slotsToFill === 1 ? '' : 's'}.`
            : `${team.name} only has $${team.remaining} left.`,
      };
    }

    return { ok: true };
  }

  draftPlayer(playerId: string, teamId: string, cost: number): boolean {
    if (!this.validateBid(playerId, teamId, cost).ok) return false;

    const player = this.players.find((p) => p.id === playerId)!;
    const team = this.teams.find((t) => t.id === teamId)!;

    player.isDrafted = true;
    player.draftedBy = teamId;
    player.draftCost = cost;
    player.pickNumber = this.draftedCount + 1;

    team.spent += cost;
    team.remaining -= cost;
    team.roster[player.position]++;
    team.projectedTotal += player.projectedPoints;

    this.draftedCount++;
    this.history.push({ playerId, teamId, cost });
    this.updateTeamMetrics(team);
    this.persist();

    return true;
  }

  /** Takes back the most recent pick. Returns the undone pick, or null. */
  undoLastPick(): { player: Player; team: Team; cost: number } | null {
    const last = this.history.pop();
    if (!last) return null;

    const player = this.players.find((p) => p.id === last.playerId);
    const team = this.teams.find((t) => t.id === last.teamId);
    if (!player || !team) return null;

    player.isDrafted = false;
    delete player.draftedBy;
    delete player.draftCost;
    delete player.pickNumber;

    team.spent -= last.cost;
    team.remaining += last.cost;
    team.roster[player.position] = Math.max(0, team.roster[player.position] - 1);
    team.projectedTotal -= player.projectedPoints;

    this.draftedCount = Math.max(0, this.draftedCount - 1);
    this.updateTeamMetrics(team);
    this.persist();

    return { player, team, cost: last.cost };
  }

  /**
   * Whose turn it is to nominate.
   *
   * Derived from the number of picks made rather than stored, so it can never
   * drift out of step with the draft and needs nothing extra synchronised if
   * this ever runs on more than one screen.
   */
  getNominatingTeam(): Team | undefined {
    if (!this.teams.length) return undefined;
    return this.teams[this.draftedCount % this.teams.length];
  }

  /** Nomination order from here, starting with whoever is up. */
  getNominationOrder(count = 4): Team[] {
    return Array.from(
      { length: Math.min(count, this.teams.length) },
      (_, offset) => this.teams[(this.draftedCount + offset) % this.teams.length]
    );
  }

  /**
   * How the room is behaving, as numbers a bidder can act on.
   *
   * Inflation above 1 means more money is chasing less value than the list
   * prices assume, so everything left will go for more than it says on the tin.
   * The premium is what has actually happened so far: what the room paid
   * divided by what we said those players were worth.
   */
  getMarketState(): MarketState {
    const drafted = this.players.filter((p) => p.isDrafted);
    const spent = drafted.reduce((total, p) => total + (p.draftCost ?? 0), 0);
    const listed = drafted.reduce((total, p) => total + p.estimatedValue, 0);

    const positions: PlayerPosition[] = ['QB', 'RB', 'WR', 'TE', 'K', 'DST'];
    const scarcity = positions.map((position) => {
      const startable = this.players.filter((p) => p.position === position && p.estimatedValue > 1);
      const sold = drafted.filter((p) => p.position === position);
      const soldFor = sold.reduce((total, p) => total + (p.draftCost ?? 0), 0);
      const soldList = sold.reduce((total, p) => total + p.estimatedValue, 0);

      // The drop from the best player left to the fifth-best: how much it costs
      // to wait. A big cliff is why a position becomes urgent.
      const remaining = startable
        .filter((p) => !p.isDrafted)
        .sort((a, b) => b.projectedPoints - a.projectedPoints);
      const cliff =
        remaining.length > 4
          ? Math.round(remaining[0].projectedPoints - remaining[4].projectedPoints)
          : 0;

      return {
        position,
        gone: startable.filter((p) => p.isDrafted).length,
        total: startable.length,
        tierOneLeft: this.players.filter(
          (p) => p.position === position && p.tier === 1 && !p.isDrafted
        ).length,
        /** What the room paid for this position against our list, once two have sold. */
        premium: sold.length >= 2 && soldList > 0 ? soldFor / soldList : null,
        sold: sold.length,
        cliff,
      };
    });

    return {
      inflation: this.calculateMarketInflation(),
      premium: listed > 0 ? spent / listed : null,
      moneyLeft: this.teams.reduce((total, team) => total + team.remaining, 0),
      valueLeft: this.players
        .filter((p) => !p.isDrafted && p.estimatedValue > 1)
        .reduce((total, p) => total + p.estimatedValue, 0),
      scarcity,
    };
  }

  /**
   * Replacement level per position, straight from the generated pool.
   *
   * Deliberately read rather than recomputed: it falls out of the league shape
   * in scripts/build-player-pool.mjs, and a second definition here would be a
   * third copy of LEAGUE to keep in step.
   */
  getReplacementLevel(position: PlayerPosition): number | null {
    const table = (poolData as { replacement?: Record<string, number> }).replacement;
    return table?.[position] ?? null;
  }

  getLeagueShape(): { teams: number; budget: number; rosterSize: number } {
    const league = (poolData as { league?: { teams: number; budget: number; rosterSize: number } })
      .league;
    return league ?? { teams: 12, budget: 200, rosterSize: 16 };
  }

  /**
   * What a hypothetical purchase does to the rest of a roster.
   *
   * The number that actually decides a bid is not the price — it is what is left
   * per slot afterwards, and whether that still buys starters. This answers it
   * without committing anything.
   */
  simulateSpend(
    teamId: string,
    cost: number
  ): {
    remaining: number;
    slotsLeft: number;
    perSlot: number;
    /** Slots that must be filled at a dollar to stay legal. */
    minimumHold: number;
    /** True only when the amount is a real bid the reserve rules would allow. */
    /** Best player still on the board that the leftover budget could afford. */
    affordable: Player | null;
    legal: boolean;
  } | null {
    const team = this.teams.find((t) => t.id === teamId);
    if (!team) return null;

    const filled = Object.values(team.roster).reduce((a, b) => a + b, 0);
    const slotsLeft = Math.max(0, MAX_ROSTER_SIZE - filled - 1);
    const remaining = team.remaining - cost;
    // Every unfilled starting slot still needs a dollar in reserve, exactly as
    // validateBid enforces it.
    const minimumHold = Math.max(0, STARTING_LINEUP_SIZE - filled - 1);
    const spendable = remaining - minimumHold;
    const affordable =
      spendable > 0
        ? (this.players
            .filter((p) => !p.isDrafted && p.id !== undefined && p.estimatedValue <= spendable)
            .sort((a, b) => b.projectedPoints - a.projectedPoints)[0] ?? null)
        : null;

    return {
      remaining,
      slotsLeft,
      perSlot: slotsLeft > 0 ? Math.max(0, remaining - minimumHold) / slotsLeft : 0,
      minimumHold,
      affordable,
      legal: remaining >= minimumHold && cost >= 1,
    };
  }

  /**
   * Where our board and the market's disagree, in dollars.
   *
   * `market.edge` is a difference of ranks; this converts it into what it is
   * worth tonight by pricing each player at the room's current inflation. A
   * player the consensus ranks 40 spots below us is only a bargain if he is
   * still going to be cheap when he comes up.
   */
  getBargains(limit = 24): Array<{
    player: Player;
    edge: number;
    listed: number;
    projectedCost: number;
    saving: number;
  }> {
    const inflation = this.calculateMarketInflation();
    return this.players
      .filter((p) => !p.isDrafted && p.market?.consensusRank != null && p.estimatedValue > 1)
      .map((player) => {
        const listed = player.estimatedValue;
        // The room bids off consensus, so the expected price tracks the market
        // rank, not ours; inflation moves both.
        const projectedCost = Math.max(1, Math.round(listed * inflation));
        return {
          player,
          edge: player.market?.edge ?? 0,
          listed,
          projectedCost,
          saving: Math.round(listed - projectedCost + (player.market?.edge ?? 0) * 0.12),
        };
      })
      .sort((a, b) => b.edge - a.edge || b.listed - a.listed)
      .slice(0, limit);
  }

  /** Every pick so far, grouped for the league board. */
  getDraftBoard(): Array<{
    team: Team;
    picks: Array<{ player: Player; cost: number; pickNumber: number }>;
  }> {
    return this.teams.map((team) => ({
      team,
      picks: this.players
        .filter((p) => p.draftedBy === team.id)
        .map((p) => ({ player: p, cost: p.draftCost ?? 0, pickNumber: p.pickNumber ?? 0 }))
        .sort((a, b) => a.pickNumber - b.pickNumber),
    }));
  }

  canUndo(): boolean {
    return this.history.length > 0;
  }

  private updateTeamMetrics(team: Team): void {
    const teamPlayers = this.players.filter((p) => p.draftedBy === team.id);

    // Calculate strength score (average projected points)
    team.strengthScore =
      teamPlayers.length > 0
        ? teamPlayers.reduce((sum, p) => sum + p.projectedPoints, 0) / teamPlayers.length
        : 0;

    // Calculate risk score (average injury risk)
    const riskValues = { LOW: 1, MEDIUM: 2, HIGH: 3 };
    team.riskScore =
      teamPlayers.length > 0
        ? teamPlayers.reduce((sum, p) => sum + riskValues[p.injuryRisk], 0) / teamPlayers.length
        : 0;

    // Calculate depth score (players beyond starting lineup). Every position
    // needs an entry: an undefined starter count makes the subtraction NaN.
    const startingPositions: RosterCounts = { QB: 1, RB: 2, WR: 2, TE: 1, K: 1, DST: 1 };
    team.depthScore = Object.entries(team.roster).reduce((total, [pos, count]) => {
      const starting = startingPositions[pos as PlayerPosition] ?? 0;
      return total + Math.max(0, count - starting);
    }, 0);

    // Calculate injury insurance (handcuff value)
    team.injuryInsurance = teamPlayers.reduce((sum, p) => sum + (p.handcuffValue ?? 0), 0) / 100;
  }

  /** Starting slots a team must fill, which is what makes a position urgent. */
  private static readonly STARTERS: Record<PlayerPosition, number> = {
    QB: 1,
    RB: 2,
    WR: 3,
    TE: 1,
    K: 1,
    DST: 1,
  };

  /**
   * What this player should cost this team, right now.
   *
   * Three real forces move a price away from the list value: how much money is
   * still chasing how much value (inflation), how badly this team still needs
   * the position (need), and how little of the position is left (scarcity).
   * Nothing here is invented — each one is read off the current draft state.
   */
  generateDraftAnalytics(playerId: string, teamId: string): DraftAnalytics {
    const player = this.players.find((p) => p.id === playerId);
    const team = this.teams.find((t) => t.id === teamId);
    if (!player || !team) throw new Error('Player or team not found');

    const marketInflation = this.calculateMarketInflation();
    const needMultiplier = this.calculateNeedMultiplier(player.position, team);
    const positionScarcity = this.calculatePositionScarcity(player.position);

    const adjustedValue =
      player.baseValue * marketInflation * needMultiplier * (1 + positionScarcity * 0.15);

    // Injury and age history discount what we are willing to commit.
    const riskFactor =
      (player.injuryRisk === 'HIGH' ? 0.88 : player.injuryRisk === 'MEDIUM' ? 0.95 : 1) *
      (player.ageRisk === 'HIGH' ? 0.9 : player.ageRisk === 'MEDIUM' ? 0.96 : 1);
    const riskAdjustedValue = adjustedValue * riskFactor;

    const filled = Object.values(team.roster).reduce((total, count) => total + count, 0);
    const slotsToFill = Math.max(0, STARTING_LINEUP_SIZE - filled - 1);
    const spendable = Math.max(1, team.remaining - slotsToFill);

    const targetBid = Math.max(1, Math.round(riskAdjustedValue));
    const maxBid = Math.max(1, Math.min(Math.round(riskAdjustedValue * 1.15), spendable));
    const openingBid = Math.max(1, Math.round(targetBid * 0.6));

    return {
      baseValue: player.baseValue,
      adjustedValue: Math.round(adjustedValue),
      maxBid,
      openingBid,
      targetBid,
      // The first dollar you should not spend.
      walkAwayPoint: maxBid + 1,
      needMultiplier: Math.round(needMultiplier * 100) / 100,
      scarcityFactor: Math.round(positionScarcity * 100) / 100,
      confidenceLevel: this.calculateConfidenceLevel(player),
      marketInflation: Math.round(marketInflation * 100) / 100,
      positionScarcity: Math.round(positionScarcity * 100) / 100,
      valueOverBaseline: player.valueOverReplacement,
      riskAdjustedValue: Math.round(riskAdjustedValue),
      optimalBidRange: [openingBid, maxBid],
      injuryAdjustment: Math.round((1 - riskFactor) * 100) / 100,
      ageAdjustment: player.ageRisk === 'LOW' ? 0 : player.ageRisk === 'MEDIUM' ? 0.04 : 0.1,
      competitionRisk: player.competitionLevel === 'LOCKED_STARTER' ? 0 : 0.15,
      rosterId: team.id,
    };
  }

  /**
   * Dollars still available divided by the value still on the board. Above 1.0
   * the room is going to overpay for what is left; below it, bargains.
   */
  private calculateMarketInflation(): number {
    const openSlots = this.teams.reduce(
      (total, team) =>
        total +
        Math.max(0, STARTING_LINEUP_SIZE - Object.values(team.roster).reduce((a, b) => a + b, 0)),
      0
    );
    const moneyLeft = this.teams.reduce((total, team) => total + team.remaining, 0) - openSlots;
    const valueLeft = this.players
      .filter((p) => !p.isDrafted && p.estimatedValue > 1)
      .reduce((total, p) => total + p.estimatedValue, 0);
    if (valueLeft <= 0) return 1;
    return Math.max(0.6, Math.min(1.8, moneyLeft / valueLeft));
  }

  /**
   * How urgently this team still needs the position.
   *
   * An empty slot early is not urgent — there is a whole draft left to fill it.
   * The premium therefore grows with how much of the position is already gone,
   * which is what actually makes a hole expensive.
   */
  private calculateNeedMultiplier(position: string, team: Team): number {
    const required = AuctionDraftService.STARTERS[position as PlayerPosition] ?? 1;
    const have = team.roster[position as PlayerPosition] ?? 0;
    const unfilled = Math.max(0, required - have);
    const gone = this.calculatePositionScarcity(position);
    return 1 + Math.min(0.45, unfilled * 0.18 * gone);
  }

  /** Share of the position's startable players already off the board. */
  private calculatePositionScarcity(position: string): number {
    const startable = this.players.filter((p) => p.position === position && p.estimatedValue > 1);
    if (!startable.length) return 0;
    const gone = startable.filter((p) => p.isDrafted).length;
    return gone / startable.length;
  }

  /** How much of this player we have actually seen, on a 0-100 scale. */
  private calculateConfidenceLevel(player: Player): number {
    const games = player.lastSeasonGames ?? 0;
    const sample = Math.min(1, games / 17);
    const steadiness = (player.consistency ?? 5) / 10;
    return Math.round((sample * 0.6 + steadiness * 0.4) * 100);
  }

  isDraftComplete(): boolean {
    return this.draftedCount >= 60;
  }

  searchPlayers(query: string): Player[] {
    if (!query) return this.players;
    return this.players.filter(
      (p) =>
        p.name.toLowerCase().includes(query.toLowerCase()) ||
        p.position.toLowerCase().includes(query.toLowerCase()) ||
        p.team.toLowerCase().includes(query.toLowerCase())
    );
  }

  getPlayerAnalytics(playerId: string, teamId: string = 'team-1'): DraftAnalytics {
    return this.generateDraftAnalytics(playerId, teamId);
  }

  getDraftedPlayers(): Player[] {
    return this.players.filter((p) => p.isDrafted);
  }

  getAvailablePlayers(): Player[] {
    return this.players.filter((p) => !p.isDrafted);
  }

  resetDraft(): void {
    this.players.forEach((p) => {
      p.isDrafted = false;
      delete p.draftedBy;
      delete p.draftCost;
      delete p.pickNumber;
    });
    this.draftedCount = 0;
    this.history = [];
    this.teams.forEach((team) => {
      team.spent = 0;
      team.remaining = team.budget;
      team.roster = EMPTY_ROSTER();
      team.projectedTotal = 0;
      // Derived metrics too: leaving these behind makes a reset draft report
      // the strength and risk of the roster it just threw away.
      team.strengthScore = 0;
      team.riskScore = 0;
      team.depthScore = 0;
      team.injuryInsurance = 0;
    });
    this.persist();
  }

  // -------------------------------------------------------------------------
  // persistence
  //
  // Only the picks are stored: replaying them rebuilds every derived number, so
  // a saved draft can never disagree with the current valuation logic.
  // -------------------------------------------------------------------------

  private persist(): void {
    try {
      if (!this.history.length) {
        localStorage.removeItem(AuctionDraftService.STORAGE_KEY);
        return;
      }
      localStorage.setItem(
        AuctionDraftService.STORAGE_KEY,
        JSON.stringify({
          version: 2,
          savedAt: new Date().toISOString(),
          budgets: this.teams.map((t) => ({ id: t.id, budget: t.budget })),
          picks: this.history,
        })
      );
    } catch {
      /* storage unavailable (private mode, quota) — the draft simply won't resume */
    }
  }

  /** Replays a saved draft. Returns how many picks were restored. */
  restore(): number {
    let saved: {
      version?: number;
      budgets?: Array<{ id: string; budget: number }>;
      picks?: Array<{ playerId: string; teamId: string; cost: number }>;
    } | null = null;
    try {
      const raw = localStorage.getItem(AuctionDraftService.STORAGE_KEY);
      saved = raw ? JSON.parse(raw) : null;
    } catch {
      saved = null;
    }
    if (!saved?.picks?.length || saved.version !== 2) return 0;

    this.resetDraft();
    for (const { id, budget } of saved.budgets ?? []) this.updateTeamBudget(id, budget);

    let restored = 0;
    for (const pick of saved.picks) {
      if (this.draftPlayer(pick.playerId, pick.teamId, pick.cost)) restored++;
    }
    return restored;
  }

  /** Whether a resumable draft is sitting in storage. */
  static hasSavedDraft(): boolean {
    try {
      return !!localStorage.getItem(AuctionDraftService.STORAGE_KEY);
    } catch {
      return false;
    }
  }

  private static readonly STORAGE_KEY = 'draft-vault:auction-draft:v2';

  getHistory(): ReadonlyArray<{ playerId: string; teamId: string; cost: number }> {
    return this.history;
  }

  getValueGrade(estimatedValue: number, actualCost: number): string {
    const ratio = actualCost / estimatedValue;
    if (ratio <= 0.8) return 'A+';
    if (ratio <= 0.9) return 'A';
    if (ratio <= 1.0) return 'B+';
    if (ratio <= 1.1) return 'B';
    if (ratio <= 1.2) return 'C';
    return 'D';
  }

  getProgressPercentage(): number {
    return (this.draftedCount / 60) * 100;
  }

  updateTeamBudget(teamId: string, budget: number): void {
    const team = this.teams.find((t) => t.id === teamId);
    if (!team) return;
    if (!Number.isFinite(budget)) return;
    // A budget below what the team already committed would leave it with
    // negative money to spend, so it cannot go under the amount already spent.
    team.budget = Math.max(team.spent, Math.round(budget));
    team.remaining = team.budget - team.spent;
  }

  getAuctionPlayers(): Player[] {
    return this.players;
  }

  getSnakeDraftPlayers(): SnakeDraftPlayer[] {
    // Return empty array since snake draft uses separate database
    return [];
  }
}
