/**
 * Identity for real NFL teams and players: colors, logos, headshots, defensive
 * personnel.
 *
 * Two tiers, deliberately:
 *   1. A curated snapshot generated by scripts/fetch-nfl-data.mjs ships in the
 *      bundle, so the first paint always has real names, colors and faces even
 *      with no network.
 *   2. refreshIdentity() then asks ESPN for today's version — mainly for injury
 *      status and mid-season team changes — caches it, and merges it on top.
 *      Every failure path falls back to tier 1 rather than surfacing an error;
 *      stale identity is much better than a blank card.
 */
import teamsData from '@/data/nfl/teams.json';
import poolData from '@/data/nfl/pool.json';
import { logWarn } from '@/lib/logger';

export interface NflTeam {
  abbr: string;
  espnId: string;
  name: string;
  nickname: string;
  location: string;
  color: string;
  altColor: string;
  logo: string;
}

export interface PlayerIdentity {
  /** nflverse gsis id, which is also the player's id in the draft pool. */
  poolId: string;
  /** ESPN athlete id, used for headshots. Null for team defenses. */
  espnId: string | null;
  name: string;
  team: string;
  position: string;
  jersey: string | null;
  age: number | null;
  experience: number | null;
  heightInches: number | null;
  weightPounds: number | null;
  college: string | null;
  headshot: string | null;
  status: string | null;
  injury: { status: string | null; detail: string | null } | null;
}

export interface DefenseUnits {
  dl: PlayerIdentity[];
  lb: PlayerIdentity[];
  db: PlayerIdentity[];
}

const ESPN_API = 'https://site.api.espn.com/apis/site/v2/sports/football/nfl';
const CACHE_KEY = 'draft-vault:nfl-identity:v1';
const CACHE_TTL_MS = 12 * 60 * 60 * 1000;
const LIVE_TIMEOUT_MS = 6000;

/** Abbreviations the auction pool spells differently from ESPN. */
const TEAM_ALIASES: Record<string, string> = {
  JAC: 'JAX',
  AZ: 'ARI',
  WAS: 'WSH',
  LA: 'LAR',
  SD: 'LAC',
  OAK: 'LV',
  STL: 'LAR',
};

export const canonicalTeam = (abbr: string): string => TEAM_ALIASES[abbr] ?? abbr;

const teams = new Map<string, NflTeam>(
  (teamsData.teams as NflTeam[]).map((team) => [team.abbr, team])
);

interface PoolEntry {
  gsis: string;
  espnId: string | null;
  name: string;
  position: string;
  team: string;
  jersey: string | null;
  age: number | null;
  experience: number | null;
  college: string | null;
}

/**
 * Identity comes straight out of the pool, which is generated from nflverse
 * rosters — so a player's name, team and face can never disagree with the
 * numbers printed beside them.
 */
const identities = new Map<string, PlayerIdentity>(
  (poolData.players as PoolEntry[]).map((entry) => [
    entry.gsis,
    {
      poolId: entry.gsis,
      espnId: entry.espnId,
      name: entry.name,
      team: entry.team,
      position: entry.position,
      jersey: entry.jersey,
      age: entry.age,
      experience: entry.experience,
      heightInches: null,
      weightPounds: null,
      college: entry.college,
      headshot: null,
      status: null,
      injury: null,
    },
  ])
);

/** Live overrides keyed by ESPN athlete id, merged over the bundled snapshot. */
let liveOverrides = new Map<string, Partial<PlayerIdentity>>();

// ---------------------------------------------------------------------------
// reads
// ---------------------------------------------------------------------------

export const getTeam = (abbr: string): NflTeam | undefined => teams.get(canonicalTeam(abbr));

export const allTeams = (): NflTeam[] => [...teams.values()];

export const getIdentity = (poolId: string): PlayerIdentity | undefined => {
  const base = identities.get(poolId);
  if (!base) return undefined;
  // Team defenses have no ESPN athlete id, so there is never a live override
  // for them and the lookup must not be attempted with a null key.
  const live = base.espnId ? liveOverrides.get(base.espnId) : undefined;
  return live ? { ...base, ...live } : base;
};

/** A team's colors, falling back to neutral ink so a card never renders unstyled. */
export const teamColors = (abbr: string): { primary: string; secondary: string } => {
  const team = getTeam(abbr);
  return { primary: team?.color ?? '#4a5568', secondary: team?.altColor ?? '#1a202c' };
};

export const teamLogo = (abbr: string): string | undefined => {
  const team = getTeam(abbr);
  if (!team) return undefined;
  return embedded().logos?.[team.abbr] ?? team.logo;
};

/**
 * Optional bundle of embedded images, injected by fully self-contained builds
 * (`npm run build:single`) so a page with no network still shows faces and
 * logos. Absent in a normal build, where the CDN serves them.
 */
interface EmbeddedAssets {
  headshots?: Record<string, string>;
  logos?: Record<string, string>;
}

const embedded = (): EmbeddedAssets =>
  (globalThis as { __DV_ASSETS__?: EmbeddedAssets }).__DV_ASSETS__ ?? {};

/**
 * ESPN's image combiner, which resizes server-side — full-size headshots are
 * ~240 KB each and there are sixty of them on the board at once.
 */
export const headshotUrl = (identity: Pick<PlayerIdentity, 'espnId'>, width = 200): string =>
  embedded().headshots?.[identity.espnId ?? ''] ??
  `https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/${identity.espnId}.png&w=${width}&h=${Math.round(
    width * 0.73
  )}&scale=crop&cquality=80`;

/**
 * Real defensive personnel for a team. Loaded on demand: the full league's
 * defensive units are ~115 KB and only matter once a defense profile opens.
 */
export const loadDefenseUnits = async (abbr: string): Promise<DefenseUnits | undefined> => {
  const module = await import('@/data/nfl/defense-units.json');
  // The generated JSON is structurally a DefenseUnits map but TypeScript widens
  // every null literal in it, so the shapes never formally overlap.
  const byTeam = (module.default ?? module).teams as unknown as Record<string, DefenseUnits>;
  return byTeam[canonicalTeam(abbr)];
};

export const snapshotMeta = (): { season: number | null; generatedAt: string } => ({
  season: (teamsData as { season?: number }).season ?? null,
  generatedAt: (teamsData as { generatedAt?: string }).generatedAt ?? '',
});

// ---------------------------------------------------------------------------
// live refresh
// ---------------------------------------------------------------------------

interface CachedLive {
  fetchedAt: number;
  overrides: Array<[string, Partial<PlayerIdentity>]>;
}

const readCache = (): CachedLive | null => {
  try {
    const raw = localStorage.getItem(CACHE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as CachedLive;
    if (Date.now() - parsed.fetchedAt > CACHE_TTL_MS) return null;
    return parsed;
  } catch {
    return null; // private mode, quota, corrupt entry — all mean "no cache"
  }
};

const writeCache = (cache: CachedLive): void => {
  try {
    localStorage.setItem(CACHE_KEY, JSON.stringify(cache));
  } catch {
    /* storage unavailable; the refresh still applies for this session */
  }
};

const fetchJSON = async (url: string, signal: AbortSignal): Promise<unknown> => {
  const res = await fetch(url, { signal });
  if (!res.ok) throw new Error(`${url} -> ${res.status}`);
  return res.json();
};

interface EspnAthlete {
  id: string;
  fullName?: string;
  position?: { abbreviation?: string };
  status?: { name?: string };
  injuries?: Array<{ status?: string; details?: { type?: string } }>;
  team?: { abbreviation?: string };
}

/**
 * Refreshes injury status and team for the pool's players from ESPN.
 *
 * Only the teams the pool actually references are fetched, so this is a handful
 * of requests rather than all thirty-two. Resolves to the number of players
 * updated, or 0 when the network is unavailable — never rejects.
 */
export const refreshIdentity = async (): Promise<number> => {
  /*
   * Somewhere that cannot reach ESPN at all, so do not try.
   *
   * The published artifact's CSP blocks every external host, and this call asks
   * for all 32 rosters — thirty-two requests that can only fail, each printed
   * to the console. The bundled snapshot already paints real names, colours and
   * faces without any of it, which is the whole reason the artifact build
   * embeds them. `build-artifact.mjs` sets the flag; nothing else does, because
   * a laptop on draft-night wifi genuinely benefits from the live injury merge.
   */
  if ((globalThis as { __DV_OFFLINE__?: boolean }).__DV_OFFLINE__) return 0;

  const cached = readCache();
  if (cached) {
    liveOverrides = new Map(cached.overrides);
    return liveOverrides.size;
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), LIVE_TIMEOUT_MS);

  try {
    const wanted = new Map<string, Set<string>>(); // espn team id -> athlete ids
    for (const player of identities.values()) {
      const team = getTeam(player.team);
      if (!team) continue;
      if (!player.espnId) continue;
      const bucket = wanted.get(team.espnId) ?? new Set<string>();
      bucket.add(player.espnId);
      wanted.set(team.espnId, bucket);
    }

    const overrides = new Map<string, Partial<PlayerIdentity>>();
    const rosters = await Promise.all(
      [...wanted.keys()].map((espnTeamId) =>
        fetchJSON(`${ESPN_API}/teams/${espnTeamId}/roster`, controller.signal).catch(() => null)
      )
    );

    for (const roster of rosters) {
      if (!roster) continue;
      const payload = roster as {
        team?: { abbreviation?: string };
        athletes?: Array<{ items?: EspnAthlete[] }>;
      };
      const teamAbbr = payload.team?.abbreviation;
      for (const group of payload.athletes ?? []) {
        for (const athlete of group.items ?? []) {
          const injury = athlete.injuries?.[0];
          overrides.set(athlete.id, {
            team: teamAbbr ?? undefined,
            status: athlete.status?.name ?? null,
            injury: injury
              ? { status: injury.status ?? null, detail: injury.details?.type ?? null }
              : null,
          });
        }
      }
    }

    if (overrides.size) {
      liveOverrides = overrides;
      writeCache({ fetchedAt: Date.now(), overrides: [...overrides.entries()] });
    }
    return overrides.size;
  } catch (error) {
    logWarn('Live NFL identity refresh unavailable; using bundled snapshot', {
      component: 'nflIdentity',
      reason: error instanceof Error ? error.message : String(error),
    });
    return 0;
  } finally {
    clearTimeout(timeout);
  }
};
