import { useState } from 'react';
import { Download, Share2, Copy, Check, FileText, Image, Table, Mail } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Player, Team } from '@/services/auctionDraftService';

interface ExportDraftProps {
  teams: Team[];
  players: Player[];
  draftedPlayers: Player[];
}

export const ExportDraft = ({ teams, players, draftedPlayers }: ExportDraftProps) => {
  const [copied, setCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const generateTextSummary = () => {
    let summary = `🏈 DRAFT VAULT - Draft Results\n`;
    summary += `${'═'.repeat(40)}\n\n`;
    summary += `📅 Date: ${new Date().toLocaleDateString()}\n`;
    summary += `👥 Teams: ${teams.length}\n`;
    summary += `🎯 Players Drafted: ${draftedPlayers.length}\n\n`;

    teams.forEach((team) => {
      const teamPlayers = draftedPlayers.filter((p) => p.draftedBy === team.id);
      summary += `\n${'─'.repeat(30)}\n`;
      summary += `📋 ${team.name}\n`;
      summary += `💰 Budget: $${team.budget} | Spent: $${team.spent} | Remaining: $${team.remaining}\n`;
      summary += `📊 Projected: ${team.projectedTotal.toFixed(1)} pts\n\n`;

      const positions = ['QB', 'RB', 'WR', 'TE'];
      positions.forEach((pos) => {
        const posPlayers = teamPlayers.filter((p) => p.position === pos);
        if (posPlayers.length > 0) {
          summary += `${pos}: `;
          summary += posPlayers.map((p) => `${p.name} ($${p.draftCost})`).join(', ');
          summary += '\n';
        }
      });
    });

    summary += `\n${'═'.repeat(40)}\n`;
    summary += `Generated by Draft Vault\n`;

    return summary;
  };

  const generateCSV = () => {
    const headers = ['Team', 'Pick', 'Player', 'Position', 'NFL Team', 'Cost', 'Projected Points', 'Value'];
    const rows = draftedPlayers.map((p) => {
      const team = teams.find((t) => t.id === p.draftedBy);
      return [
        team?.name || '',
        p.pickNumber?.toString() || '',
        p.name,
        p.position,
        p.team,
        p.draftCost?.toString() || '',
        p.projectedPoints.toString(),
        p.valueOverReplacement.toString(),
      ];
    });

    const csv = [headers, ...rows].map((row) => row.join(',')).join('\n');
    return csv;
  };

  const generateJSON = () => {
    const data = {
      exportDate: new Date().toISOString(),
      summary: {
        totalTeams: teams.length,
        totalPlayers: draftedPlayers.length,
        totalSpent: teams.reduce((sum, t) => sum + t.spent, 0),
      },
      teams: teams.map((team) => ({
        ...team,
        roster: draftedPlayers.filter((p) => p.draftedBy === team.id),
      })),
      draftOrder: draftedPlayers.sort((a, b) => (a.pickNumber || 0) - (b.pickNumber || 0)),
    };

    return JSON.stringify(data, null, 2);
  };

  const copyToClipboard = async (text: string) => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const shareViaEmail = () => {
    const subject = encodeURIComponent('Draft Vault - Draft Results');
    const body = encodeURIComponent(generateTextSummary());
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  const shareNative = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Draft Vault - Draft Results',
          text: generateTextSummary(),
        });
      } catch {
        // User cancelled or error
      }
    }
  };

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button className="btn-premium gap-2">
          <Share2 className="w-4 h-4" />
          Export & Share
        </Button>
      </DialogTrigger>
      <DialogContent className="modal-content max-w-2xl">
        <DialogHeader>
          <DialogTitle className="gradient-text text-2xl flex items-center gap-2">
            <Download className="w-6 h-6" />
            Export Draft Results
          </DialogTitle>
        </DialogHeader>

        <Tabs defaultValue="download" className="mt-4">
          <TabsList className="grid w-full grid-cols-3 tab-nav">
            <TabsTrigger value="download" className="tab-item data-[state=active]:active">
              <Download className="w-4 h-4 mr-2" />
              Download
            </TabsTrigger>
            <TabsTrigger value="share" className="tab-item data-[state=active]:active">
              <Share2 className="w-4 h-4 mr-2" />
              Share
            </TabsTrigger>
            <TabsTrigger value="copy" className="tab-item data-[state=active]:active">
              <Copy className="w-4 h-4 mr-2" />
              Copy
            </TabsTrigger>
          </TabsList>

          <TabsContent value="download" className="space-y-4 mt-4">
            <div className="grid grid-cols-3 gap-4">
              <Card
                className="glass-card cursor-pointer hover:border-primary/50 transition-all"
                onClick={() => downloadFile(generateTextSummary(), 'draft-results.txt', 'text/plain')}
              >
                <CardContent className="p-6 text-center">
                  <FileText className="w-12 h-12 mx-auto mb-3 text-primary" />
                  <h3 className="font-bold">Text File</h3>
                  <p className="text-xs text-muted-foreground">.txt format</p>
                </CardContent>
              </Card>

              <Card
                className="glass-card cursor-pointer hover:border-primary/50 transition-all"
                onClick={() => downloadFile(generateCSV(), 'draft-results.csv', 'text/csv')}
              >
                <CardContent className="p-6 text-center">
                  <Table className="w-12 h-12 mx-auto mb-3 text-green-400" />
                  <h3 className="font-bold">Spreadsheet</h3>
                  <p className="text-xs text-muted-foreground">.csv format</p>
                </CardContent>
              </Card>

              <Card
                className="glass-card cursor-pointer hover:border-primary/50 transition-all"
                onClick={() => downloadFile(generateJSON(), 'draft-results.json', 'application/json')}
              >
                <CardContent className="p-6 text-center">
                  <FileText className="w-12 h-12 mx-auto mb-3 text-yellow-400" />
                  <h3 className="font-bold">JSON Data</h3>
                  <p className="text-xs text-muted-foreground">.json format</p>
                </CardContent>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="share" className="space-y-4 mt-4">
            <div className="grid grid-cols-2 gap-4">
              <Button
                className="h-auto py-6 flex flex-col items-center gap-2 btn-secondary"
                onClick={shareViaEmail}
              >
                <Mail className="w-8 h-8" />
                <span>Email</span>
              </Button>

              {typeof navigator !== 'undefined' && 'share' in navigator && (
                <Button
                  className="h-auto py-6 flex flex-col items-center gap-2 btn-secondary"
                  onClick={shareNative}
                >
                  <Share2 className="w-8 h-8" />
                  <span>Share</span>
                </Button>
              )}
            </div>

            <div className="p-4 rounded-xl bg-secondary/30">
              <Label className="text-sm text-muted-foreground">Share Link (Coming Soon)</Label>
              <div className="flex gap-2 mt-2">
                <Input
                  value="https://draftvault.app/share/..."
                  readOnly
                  className="input-premium"
                  disabled
                />
                <Button disabled>
                  <Copy className="w-4 h-4" />
                </Button>
              </div>
            </div>
          </TabsContent>

          <TabsContent value="copy" className="space-y-4 mt-4">
            <div className="relative">
              <pre className="p-4 rounded-xl bg-secondary/50 text-xs overflow-auto max-h-[300px] whitespace-pre-wrap">
                {generateTextSummary()}
              </pre>
              <Button
                className="absolute top-2 right-2"
                size="sm"
                onClick={() => copyToClipboard(generateTextSummary())}
              >
                {copied ? (
                  <>
                    <Check className="w-4 h-4 mr-1" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4 mr-1" />
                    Copy
                  </>
                )}
              </Button>
            </div>
          </TabsContent>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
};

export default ExportDraft;
